### PR TITLE
[#1213] Regressions from #1059

### LINKED ISSUE #1213: Regressions from #1059
PR #1059 separates extracts `v_summary_charts` out of `v_summary`, while passing data through props from `v_summary` to `v_summary_charts`.

Props such as `sortingOption`, `sortingWithinOption`, `isSortingDsc`, `isSortingWithinDsc` were not passed to `v_summary_charts`, even though they were used in `openTabZoom`.

Hence, in some cases, the zoom tab is not restorable after reloading the page.

### PR DESCRIPTION
**Pull request by 0blivious**
Fixes #1213

```
With the recent merged PR #1059, the data related to sorting were not
passed from v_summary to v_summary_charts, even though
v_summary_charts uses those data within openTabZoom method.

This results in zoom tab to not be restorable at some situations, as it 
is unable to utilise the sorting options. However, the sorting options
and the call for sortFiltered is actually not needed
within the restoreZoomFiltered method. This is because the
matchZoomUser within restoreZoomFiltered will already filter out
other groups/repos. Thus, there is no need to pass those props into
v_summary_charts.

Let's remove the unnecessary parameters and methods.
```

### CODE REVIEW

**Comment by jamessspanggg** [comment]
@fzdy1914 @eugenepeh may i get your review on this? This PR will affect the usage for current users

**Comment by jamessspanggg** [comment]
@Tejas2805 @anubh-v @ang-zeyu @ccyccyccy may I ask your reviews on this to ensure that the bug no longer exists and no other bugs are introduced?

File: frontend/src/static/js/v_summary.js [hunk 1]
```diff
@@ -803,10 +803,9 @@ window.vSummary = {
 
     restoreZoomFiltered(info) {
       const {
-        zSince, zUntil, zFilterGroup, zTimeFrame, zIsMerge, zSorting, zSortingWithin,
-        zIsSortingDsc, zIsSortingWithinDsc,
+        zSince, zUntil, zTimeFrame, zIsMerge,
       } = info;
-      let filtered = [];
+      const filtered = [];
```
Comment (Tejas2805) [inline frontend/src/static/js/v_summary.js:808]: Can you just leave a comment here as to why the shift from `let` to `const`?

File: frontend/src/static/js/v_summary.js [hunk 2]
```diff
@@ -828,15 +827,6 @@ window.vSummary = {
         }
       });
 
-      const filterControl = {
```
Comment (Tejas2805) [inline frontend/src/static/js/v_summary.js:831]: This also exists around line number 300. Do you know why did we have duplicate code?

File: frontend/src/static/js/v_summary.js (hunk 1 above)
Comment (0blivious) [reply frontend/src/static/js/v_summary.js:808]: it will not be reassigned so by definition const would be better classifier. Actually this is the result of js auto correction

File: frontend/src/static/js/v_summary.js (hunk 2 above)
Comment (0blivious) [reply frontend/src/static/js/v_summary.js:831]: The one in 300 is needed as summary_charts will receive the filtered repo and display them without sorting. The line here is for zoom, which will perform sorting in its own js file.
