### PR TITLE
[#1476] Remove the highlighting when the panel is closed

### LINKED ISSUE #1476: Highlighting persists even when tab closed.
**Tell us about your environment**

https://dashboard-1466-pr-reposense-reposense.surge.sh/

**Please include the steps to reproduce the bug.**

When I close the side tab the highlighting persists.

image

**What was expected to happen?**

When I close the side tab the highlighting is removed.

### PR DESCRIPTION
**Pull request by HCY123902**
Resolves #1476 

Commit message:
```
Remove highlighting when the panel is closed by the user

The highlighting of the selected tab on the summary 
view is present when the panel is closed.

Removing the highlighting will make the indicated tab 
information more consistent.

Let's remove the highlighting when closing the panel
```

### CODE REVIEW

**Review by gerhean — APPROVED** [review]
LGTM

File: frontend/src/static/js/store.js [hunk 1]
```diff
@@ -8,6 +8,7 @@ const store = new Vuex.Store({
     fileTypeColors: {},
     loadingOverlayCount: 0,
     loadingOverlayMessage: '',
+    isTabActive: true,
```
Comment (0blivious) [inline frontend/src/static/js/store.js:11]: shouldn't this set to false by default?

Comment (HCY123902) [reply frontend/src/static/js/store.js:11]: Thanks for pointing it out. Currently, `isTabActive` is set to true by default in the main window during its initialization. It is after a tab is selected and then closed that `isTabActive` will be set to false, so I set `isTabActive` to be true here in the store initially.

**Review by 0blivious — APPROVED** [review]

File: frontend/src/static/js/main.js [hunk 2]
```diff
@@ -112,14 +112,15 @@ window.app = new window.Vue({
 
       this.isTabActive = true;
       this.tabType = tabName;
-
+      this.$store.commit('updateTabState', this.isTabActive);
```
Comment (fzdy1914) [inline frontend/src/static/js/main.js:115]: Since the tab state in Vuex is always the same with this.isTabActive. We can just remove this.isTabActive and use the one in Vuex.

**Review by fzdy1914 — CHANGES_REQUESTED** [review]

File: frontend/src/static/js/main.js (hunk 2 above)
Comment (HCY123902) [reply frontend/src/static/js/main.js]: Sure, no problem

**Review by fzdy1914 — APPROVED** [review]

**Comment by fzdy1914** [comment]
The highlighting of the selected tab on the summary view is present 
even when the panel is closed.

Removing the highlighting will make the indicated tab information 
more consistent.

Let's remove the highlighting when closing the panel.
