### PR TITLE
GitLog: handle paths in config that exist outside the repo [#398]

### LINKED ISSUE #398: Invalid file path leads to unhandled exception in Git Log
```11:00:19 - Extracting commits info for https://github.com/CS2113-AY1819S1-F10-1/main.git...
Exception in thread "main" java.lang.RuntimeException: Error returned from command git log --no-merges -i  --since="2018-09-12T00:00:00+08:00" --pretty=format:"%H|%aN|%ad|%s" --date=iso --shortstat --author="^meisbokai <.*>$\|^Neow Bo Kai <.*>$\|^meisbokai <.*>$" -- "*.adoc" -- "*.cs" -- "*.css" -- "*.fxml" -- "*.gradle" -- "*.html" -- "*.java" -- "*.js" -- "*.json" -- "*.jsp" -- "*.md" -- "*.py" -- "*.tag" -- "*.xml" ":(exclude)*.class" ":(exclude)addressbook.txt" ":(exclude)backup_data.txt" ":(exclude)exams.txt" ":(exclude)statistics.txt" ":(exclude)*.jar" ":(exclude)*.war" ":(exclude)*.ear" ":(exclude).idea/" ":(exclude)*.iml" ":(exclude)out/" ":(exclude)/bin/" ":(exclude)/data/" ":(exclude)publish.sh" ":(exclude).gradle/" ":(exclude)build/"on path repos\main\main :
fatal: Invalid path '/bin': No such file or directory

        at reposense.system.CommandRunner.runCommand(CommandRunner.java:169)
        at reposense.system.CommandRunner.gitLog(CommandRunner.java:38)
        at reposense.commits.CommitInfoExtractor.extractCommitInfos(CommitInfoExtractor.java:32)
        at reposense.commits.CommitsReporter.generateCommitSummary(CommitsReporter.java:19)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:71)
        at reposense.RepoSense.main(RepoSense.java:51)```

### PR DESCRIPTION
**Pull request by chelseyong**
Fixes #398
```
If users try to put folders existing outside of the git repository 
inside the ignore-glob-list, it will lead to a RuntimeException as the
`git log` command fails.

Let's check that the path is inside the repository, before writing it
into the ignore-glob-list and running the `git log` command.
```

### CODE REVIEW

**Comment by fzdy1914** [comment]
CI is failing...

**Comment by chelseyong** [comment]
> CI is failing...

Still fixing

File: src/main/java/reposense/git/GitUtil.java [hunk 1]
```diff
@@ -80,14 +86,51 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
+            File parentFile = canonicalRoot;
+            while (parentFile != null) {
+                if (canonicalChild.equals(parentFile)) {
+                    return true;
+                }
+                parentFile = parentFile.getParentFile();
+            }
+        } catch (IOException ex) {
+            logger.log(Level.WARNING,
+                    "File/Directory in ignore glob list cannot be accessed.", ex);
```
Comment (fzdy1914) [inline src/main/java/reposense/git/GitUtil.java]: You are also ignoring these kinds of invalid files. So, another warning should be given when the file is ignored.

File: src/main/java/reposense/git/GitUtil.java [hunk 2]
```diff
@@ -80,14 +86,51 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
+        try {
+            File canonicalRoot = repoRoot.getCanonicalFile();
+            File canonicalChild = child.getCanonicalFile();
+
+            File parentFile = canonicalRoot;
+            while (parentFile != null) {
+                if (canonicalChild.equals(parentFile)) {
+                    return true;
+                }
+                parentFile = parentFile.getParentFile();
```
Comment (fzdy1914) [inline src/main/java/reposense/git/GitUtil.java]: The logic here is a little bit weird. Why we are comparing canonicalRoot and its parents with canoicalChild?
Shouldn't we compare canonicalChild and its parents with canonicalRoot?

Comment (chelseyong) [reply src/main/java/reposense/git/GitUtil.java]: The code here is trying to trace that the `child` does not exist outside the `root` folder:
image

Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: Why a child outside the root must be a parent of root?

**Comment by fzdy1914** [comment]
Do note the codacy failure.

File: src/main/java/reposense/git/GitUtil.java (hunk 2 above)
Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: For example, the parent root is A/B, the child root is A/C.

Wouldn't it be more straight forward to just check if the child is inside the root?

Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: i.e. The parent root is A/B/C and the child root is A/B/C/D/E/F, we just check if A/B/C/D/E/F or A/B/C/D/E or A/B/C/D or A/B/C equals the parent root A/B/C?

Comment (chelseyong) [reply src/main/java/reposense/git/GitUtil.java]: > Why a child outside the root must be a parent of root?

That's to handle special situations and prevent runtime exception.

Comment (chelseyong) [reply src/main/java/reposense/git/GitUtil.java]: > i.e. The parent root is A/B/C and the child root is A/B/C/D/E/F, we just check if A/B/C/D/E/F or A/B/C/D/E or A/B/C/D or A/B/C equals the parent root A/B/C?

The example is not valid for this situation.

Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: > > Why a child outside the root must be a parent of root?
> 
> That's to handle special situations and prevent runtime exception.

Do you mean that the child passed in the function is either a parent of the root or inside the root? Can you explain why is so?

Comment (chelseyong) [reply src/main/java/reposense/git/GitUtil.java]: Yes.
Special situations like if users try to put folders existing outside of the git repository 
inside the ignore-glob-list, e.g. `../bin`, this will lead to `git log` creating a runtime exception.

Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: I have tested the globs mentioned in https://github.com/reposense/RepoSense/issues/398#issuecomment-470583555 and the problem is not solved. i.e. add `../nonExisting` will still result in runtime error.

Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: The problem is solved after I change the code to below:
```
    static boolean pathExistsInRepo(File repoRoot, String path) {
        String validPath = path;
        if (path.contains("/*")) {
            validPath = path.substring(0, path.indexOf(("/*")));
        } else if (path.contains("*")) { // not in directories
            return true;
        }
        return childIsInsideRepo(repoRoot, new File(repoRoot, validPath));
    }

    static boolean childIsInsideRepo(File repoRoot, File child) {
        try {
            File rootFile = repoRoot.getCanonicalFile();
            File childFile = child.getCanonicalFile();

            while (childFile != null) {
                if (childFile.equals(rootFile)) {
                    return true;
                }
                childFile = childFile.getParentFile();
            }
        } catch (IOException ex) {
            logger.log(Level.WARNING, "File system queries are needed.", ex);
            return false;
        } catch (SecurityException ex) {
            logger.log(Level.WARNING, "File cannot be accessed.", ex);
            return false;
        }
        return false;
    }
```

Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: > Yes.
> Special situations like if users try to put folders existing outside of the git repository
> inside the ignore-glob-list, e.g. `../bin`, this will lead to `git log` creating a runtime exception.

`../bin` will go the folder of with name `bin` in the same parent with the root but itself is not the parent of root.

You should try to add ignore glob list in author-csv to test.

Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: image
This is the repo csv I am using.

Comment (chelseyong) [reply src/main/java/reposense/git/GitUtil.java]: I get what you mean now. 
Didn't check specifically for `../bin` in the test case, but `../*java` passes the test.

Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: You may also add a `.exist()` to test whether the child exists. But not so sure if it is necessary. (Don't know how git glob works)

File: src/main/java/reposense/git/GitUtil.java (hunk 1 above)
Comment (fzdy1914) [reply src/main/java/reposense/git/GitUtil.java]: > You are also ignoring these kinds of invalid files. So, another warning should be given when the file is ignored.

What I mean here is that you should give the user warning that there is an invalid file in ignore-glob but not just ignoring it.

**Comment by chelseyong** [comment]
> Do note the codacy failure.

Not sure whether to standardize the coding style by not putting the access modifier for the function:
https://github.com/reposense/RepoSense/blob/038f645dd8bb0940009bee122f053ae74b89d0a5/src/main/java/reposense/git/GitUtil.java#L120

Or put access modifier to fix codacy.

The frontend tests are also failing, though it was not touched here.

@reposense/devs pls advise :)

**Comment by fzdy1914** [comment]
> > Do note the codacy failure.
> 
> Not sure whether to standardize the coding style by not putting the access modifier for the function:
> [RepoSense/src/main/java/reposense/git/GitUtil.java](https://github.com/reposense/RepoSense/blob/038f645dd8bb0940009bee122f053ae74b89d0a5/src/main/java/reposense/git/GitUtil.java#L120)
> 
> Line 120 in [038f645](/reposense/RepoSense/commit/038f645dd8bb0940009bee122f053ae74b89d0a5)
> 
>  static boolean childIsInsideRepo(File repoRoot, File child) { 
> Or put access modifier to fix codacy.
> 
> The frontend tests are also failing, though it was not touched here.
> 
> @reposense/devs pls advise :)

From my perspective, putting modifier to the static method is fine.

File: src/main/java/reposense/git/GitUtil.java [hunk 3]
```diff
@@ -80,14 +86,54 @@ static String convertToGitFormatsArgs(List<Format> formats) {
     /**
      * Returns the {@code String} command to specify the globs to exclude for `git log` command.
      */
-    static String convertToGitExcludeGlobArgs(List<String> ignoreGlobList) {
+    public static String convertToGitExcludeGlobArgs(File root, List<String> ignoreGlobList) {
         StringBuilder gitExcludeGlobArgsBuilder = new StringBuilder();
         final String cmdFormat = " " + addQuote(":(exclude)%s");
         ignoreGlobList.stream()
-                .filter(item -> !item.isEmpty())
+                .filter(item -> !item.isEmpty() && isValidPath(root, item))
```
Comment (fzdy1914) [inline src/main/java/reposense/git/GitUtil.java]: It seems that my explanation in this https://github.com/reposense/RepoSense/pull/592#discussion_r264026681 is not clear enough.

I mean that this filter will automatically exclude the invalid path which may not throw exceptions. So, when ignoring these kinds of invalid paths, it is better to give a log message to warn the user that, there is an invalid path in the ignoreGlobList and this path is skipped. Having this message, the user will realize that there may be a mistake in the csv file.

**Comment by eugenepeh** [comment]
```
Or put access modifier to fix codacy.

The frontend tests are also failing, though it was not touched here.

@reposense/devs pls advise :)
```
Yes, put the modifier.

File: src/main/java/reposense/git/GitUtil.java [hunk 4]
```diff
@@ -80,14 +86,59 @@ static String convertToGitFormatsArgs(List<Format> formats) {
     /**
      * Returns the {@code String} command to specify the globs to exclude for `git log` command.
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitUtil.java]: perhaps explain the use of `root` in the javadocs?

File: src/main/java/reposense/git/GitUtil.java [hunk 5]
```diff
@@ -80,14 +86,59 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
-                .filter(item -> !item.isEmpty())
+                .filter(item -> !item.isEmpty() && isValidPath(root, item))
                 .map(ignoreGlob -> String.format(cmdFormat, ignoreGlob))
                 .forEach(gitExcludeGlobArgsBuilder::append);
 
         return gitExcludeGlobArgsBuilder.toString();
     }
+
+    /**
+     * Returns true if the {@code String} path is inside the current repository
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitUtil.java]: same here, should include in javadocs that logging will be performed.

File: src/main/java/reposense/git/GitUtil.java [hunk 6]
```diff
@@ -80,14 +86,59 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
+        if (!isChildInsideRepo) {
+            logger.log(Level.WARNING, path + " will be skipped as this file is outside the repo.");
+        }
+        return isChildInsideRepo;
+    }
+
+    /**
+     * Returns true if the child path is inside repository folder
+     * @throws IOException if file system queries are needed
+     * @throws SecurityException if file permission rights are needed
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitUtil.java]: this method already handled the error, so nothing is being thrown.

File: src/main/java/reposense/system/CommandRunner.java [hunk 7]
```diff
@@ -50,7 +50,7 @@ public static String runCommand(Path path, String command) {
             return outputGobbler.getValue();
         } else {
             String errorMessage = "Error returned from command ";
-            errorMessage += command + "on path ";
+            errorMessage += command + " on path ";
```
Comment (eugenepeh) [inline src/main/java/reposense/system/CommandRunner.java]: doesnt seems to fit the purpose of this PR

File: src/main/java/reposense/git/GitUtil.java [hunk 8]
```diff
@@ -79,15 +85,60 @@ static String convertToGitFormatsArgs(List<Format> formats) {
 
     /**
      * Returns the {@code String} command to specify the globs to exclude for `git log` command.
+     * Also checks that every file in {@code String} file is within the given repository {@code File} root
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitUtil.java]: When citing the parameters, can just use the parameter name e.g. `{@code ignoreGlobList}`.
The `{@code String}` in the above header was used to described the return value as there was only a given type.

File: src/main/java/reposense/git/GitUtil.java (hunk 5 above)
Comment (eugenepeh) [reply src/main/java/reposense/git/GitUtil.java]: Same for here `{@code String}`. Missed that out earlier.

File: src/main/java/reposense/git/GitUtil.java [hunk 9]
```diff
@@ -79,15 +85,60 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
         return gitExcludeGlobArgsBuilder.toString();
     }
+
+    /**
+     * Returns true if the {@code path} is inside the current repository
+     * Produces log messages when the invalid file path is skipped
+     */
+    public static boolean isValidPath(File repoRoot, String path) {
+        String validPath = path;
+        if (path.startsWith("/") || path.startsWith("\\")) {
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitUtil.java]: instead of doing this, is it possible to use PathMatcher?
https://stackoverflow.com/questions/24677662/match-path-string-using-glob-in-java

File: src/test/java/reposense/git/GitLogTest.java [hunk 10]
```diff
@@ -77,6 +77,47 @@ public void gitLog_authorIgnoreAllJavaFiles_success() {
...
+        content = GitLog.get(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberExpectedCommitsToGitLogLines(8, content));
+
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("collate.md"));
+        content = GitLog.get(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberExpectedCommitsToGitLogLines(8, content));
+
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("./java"));
+        content = GitLog.get(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberExpectedCommitsToGitLogLines(8, content));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: Doesn't seems quite right to have all the expected result to be the same when its working.
In order word, this doesn't seems to be the best way to test it.

Could you create a new testutil to sum and compared the number of files changed instead?

File: src/test/java/reposense/util/TestUtil.java [hunk 11]
```diff
@@ -141,6 +142,29 @@ public static boolean compareNumberExpectedCommitsToGitLogLines(int expectedNumb
...
+    /**
+     * Returns true if the {@code expectedNumberFilesChanged} is equal to the actual number of files changed in
+     * {@code gitLogResult}
+     */
+    public static boolean compareNumberFilesChanged(int expectedNumberFilesChanged, String gitLogResult) {
+        // if git log result is empty, then there are no files changed
+        if (gitLogResult.isEmpty()) {
+            return expectedNumberFilesChanged == 0;
+        }
+        // 2nd line of each commit has info of the changed file
```
Comment (yamidark) [inline src/test/java/reposense/util/TestUtil.java]: This comment, and what the segment below doing doesn't seem to the same thing?

File: src/main/java/reposense/git/GitUtil.java [hunk 12]
```diff
@@ -79,15 +89,51 @@ static String convertToGitFormatsArgs(List<Format> formats) {
 
     /**
      * Returns the {@code String} command to specify the globs to exclude for `git log` command.
+     * Also checks that every file in {@code ignoreGlobList} is within the given repository {@code root}
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitUtil.java]: I think `checks that every glob in {@code ignoreGlobList} only targets files within the given repository {@code root}` is more correct?

File: src/main/java/reposense/git/GitUtil.java [hunk 13]
```diff
@@ -79,15 +89,51 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
      */
-    static String convertToGitExcludeGlobArgs(List<String> ignoreGlobList) {
+    public static String convertToGitExcludeGlobArgs(File root, List<String> ignoreGlobList) {
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitUtil.java]: need a few unit test on this method.

File: src/main/java/reposense/git/GitUtil.java [hunk 14]
```diff
@@ -79,15 +89,51 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
                 .forEach(gitExcludeGlobArgsBuilder::append);
 
         return gitExcludeGlobArgsBuilder.toString();
     }
+
+    /**
+     * Returns true if the {@code path} is inside the current repository
+     * Produces log messages when the invalid file path is skipped
+     */
+    public static boolean isValidPath(File repoRoot, String path) {
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitUtil.java]: seems like this method is only used internally, can set to private in that case.

File: src/main/java/reposense/git/GitUtil.java (hunk 13 above)
Comment (chelseyong) [reply src/main/java/reposense/git/GitUtil.java]: Is it appropriate to put these unit tests in `GitLogTest`?

File: src/main/java/reposense/git/GitLog.java [hunk 15]
```diff
@@ -10,10 +10,12 @@
...
 /**
  * Contains git log related functionalities.
- * Git log is responsible to obtain the commit logs and the authors' info.
  */
 public class GitLog {
 
+    /**
+     * Responsible for obtaining the commit logs and the authors' info.
+     */
     public static String get(RepoConfiguration config, Author author) {
```
Comment (yamidark) [inline src/main/java/reposense/git/GitLog.java]: The Javadocs for methods, should be more of explaining what the method is doing, rather than just saying what it is responsible for. Like in this case, it should be saying something like:
`Returns the git commit log info of {@code Author}, in the repository specified in {@code config}`

File: src/test/java/reposense/util/TestUtil.java [hunk 16]
```diff
@@ -141,6 +142,29 @@ public static boolean compareNumberExpectedCommitsToGitLogLines(int expectedNumb
...
+    public static boolean compareNumberFilesChanged(int expectedNumberFilesChanged, String gitLogResult) {
+        // if git log result is empty, then there are no files changed
+        if (gitLogResult.isEmpty()) {
+            return expectedNumberFilesChanged == 0;
+        }
+        String[] changesLogged = gitLogResult.split("\n");
+        HashSet<String> filesChanged = new HashSet<>();
+        // Checks the 2nd line of each commit which contains info of the changed file
+        for (int i = 1; i < changesLogged.length; i += 4) {
+            String log = changesLogged[i];
```
Comment (yamidark) [inline src/test/java/reposense/util/TestUtil.java]: Can we start `int i = 0`, and get the `String log = changesLogged[i + 1]`, easier for us to know that we are getting the 2nd line in each iteration.

File: src/main/java/reposense/git/GitLog.java [hunk 17]
```diff
@@ -10,10 +10,12 @@
 
 /**
  * Contains git log related functionalities.
- * Git log is responsible to obtain the commit logs and the authors' info.
```
[the remark this answers is not in the document]
Comment (chelseyong) [reply src/main/java/reposense/git/GitLog.java]: Originally is because this line seems to belong to the `get` method instead, now that there are 2 methods in this class, it may seem inappropriate to put it there. 
Will put it back.

File: src/main/java/reposense/git/GitUtil.java (hunk 13 above)
Comment (eugenepeh) [reply src/main/java/reposense/git/GitUtil.java]: Uh no, when the method under test is from the GitUtil, it would be best to put it under GitUtilTest.

Comment (chelseyong) [reply src/main/java/reposense/git/GitUtil.java]: Noted. Have made the changes.

File: src/main/java/reposense/git/GitLog.java [hunk 18]
```diff
@@ -14,6 +14,10 @@
  */
 public class GitLog {
 
+    /**
+     * Returns the git commit log info of {@code Author},
+     * in the repository specified in {@code config}
```
Comment (yamidark) [inline src/main/java/reposense/git/GitLog.java]: This can be in a single line (max 120 chars in single line for `java` files). Also, no need to split into newlines if they are not separate points/sentences.

File: src/main/java/reposense/git/GitUtil.java [hunk 19]
```diff
@@ -79,15 +89,51 @@ static String convertToGitFormatsArgs(List<Format> formats) {
 
     /**
      * Returns the {@code String} command to specify the globs to exclude for `git log` command.
+     * Also checks that every glob in {@code ignoreGlobList} only targets files within the given repository {@code root}
```
Comment (yamidark) [inline src/main/java/reposense/git/GitUtil.java]: Index `.` missing at end of sentence.

File: src/test/java/reposense/util/TestUtil.java [hunk 20]
```diff
@@ -141,6 +142,29 @@ public static boolean compareNumberExpectedCommitsToGitLogLines(int expectedNumb
         return expectedNumberCommits * 3 - 1 == gitLogResult.split("\n").length;
     }
 
+    /**
+     * Returns true if the {@code expectedNumberFilesChanged} is equal to the actual number of files changed in
+     * {@code gitLogResult}
```
Comment (yamidark) [inline src/test/java/reposense/util/TestUtil.java]: Index `.` missing here as well

File: src/test/java/reposense/git/GitUtilTest.java [hunk 21]
```diff
@@ -0,0 +1,46 @@
...
+    public void gitUtil_convertToGitExcludeGlobArgs_success() {
+        File repoRoot = new File(config.getRepoRoot());
+        final String cmdFormat = " " + addQuote(":(exclude)%s");
+        final String emptyResult = "";
+
+        String result = convertToGitExcludeGlobArgs(repoRoot, Collections.EMPTY_LIST);
+        Assert.assertEquals(result, emptyResult);
+
+        result = convertToGitExcludeGlobArgs(repoRoot, Collections.singletonList("**.js"));
+        Assert.assertEquals(result, String.format(cmdFormat, "**.js"));
```
Comment (yamidark) [inline src/test/java/reposense/git/GitUtilTest.java]: By convention, `expected` is the 1st argument, and `actual` is the 2nd argument when we use `assertEquals`.

File: src/main/java/reposense/git/GitUtil.java [hunk 22]
```diff
@@ -79,15 +89,51 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
      */
-    static String convertToGitExcludeGlobArgs(List<String> ignoreGlobList) {
+    public static String convertToGitExcludeGlobArgs(File root, List<String> ignoreGlobList) {
         StringBuilder gitExcludeGlobArgsBuilder = new StringBuilder();
         final String cmdFormat = " " + addQuote(":(exclude)%s");
         ignoreGlobList.stream()
-                .filter(item -> !item.isEmpty())
+                .filter(item -> !item.isEmpty() && isValidPath(root, item))
```
Comment (yamidark) [inline src/main/java/reposense/git/GitUtil.java]: Let's add the `empty` string check inside the `isValidPath` method as well, so we don't need to have 2 different boolean value here.

File: src/main/java/reposense/git/GitUtil.java [hunk 23]
```diff
@@ -79,15 +89,51 @@ static String convertToGitFormatsArgs(List<Format> formats) {
...
                 .map(ignoreGlob -> String.format(cmdFormat, ignoreGlob))
                 .forEach(gitExcludeGlobArgsBuilder::append);
 
         return gitExcludeGlobArgsBuilder.toString();
     }
+
+    /**
+     * Returns true if the {@code path} is inside the current repository
+     * Produces log messages when the invalid file path is skipped
```
Comment (yamidark) [inline src/main/java/reposense/git/GitUtil.java]: Missing index `.` at end of each sentence.

File: src/main/java/reposense/git/GitLog.java (hunk 18 above)
Comment (chelseyong) [reply src/main/java/reposense/git/GitLog.java]: The whole line is actually more than 120 chars.

Comment (yamidark) [reply src/main/java/reposense/git/GitLog.java]: Whoops, then break the line at the word which passes the limit.

File: src/test/java/reposense/git/GitLogTest.java [hunk 24]
```diff
@@ -64,17 +64,69 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+
+        // Existing file is ignored
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("annotationTest.java"));
+        String content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(5, content));
+
+        // Non-existing files that are valid
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("**collate"));
+        content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(6, content));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: lets make all these test more relevant (show some changes) to the alpha repo. 
https://github.com/reposense/testrepo-Alpha

E.g. **collate is not found in testrepo alpha, prob use **11612 or something.

File: src/test/java/reposense/git/GitLogTest.java [hunk 25]
```diff
@@ -64,17 +64,69 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
 
-        String content = GitLog.get(config, ignoreAllJavaFilesAuthor);
-        Assert.assertTrue(TestUtil.compareNumberExpectedCommitsToGitLogLines(2, content));
+        String content = GitLog.getWithFiles(config, ignoreAllJavaFilesAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(0, content));
+    }
+
+    @Test
+    public void gitLog_authorIgnoreValidFilePath_success() {
+        config.setFormats(Collections.singletonList(new Format("java")));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: lets not set any formats so that we can utilize more files for this test

File: src/test/java/reposense/git/GitLogTest.java [hunk 26]
```diff
@@ -64,17 +64,69 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+
+        ignoreInvalidFileAuthor.setIgnoreGlobList(Collections.singletonList("../bin"));
+        String content = GitLog.getWithFiles(config, ignoreInvalidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(6, content));
+
+        ignoreInvalidFileAuthor.setIgnoreGlobList(Collections.singletonList("../*.java"));
+        content = GitLog.getWithFiles(config, ignoreInvalidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(6, content));
+
+        ignoreInvalidFileAuthor.setIgnoreGlobList(Collections.singletonList("/collate"));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: same for these, can set to `/newPos` instead

File: src/test/java/reposense/git/GitLogTest.java (hunk 24 above)
Comment (chelseyong) [reply src/test/java/reposense/git/GitLogTest.java]: `.attach_pid11612` is not registered in the list of files. Perhaps because it is not in the list of `DEFAULT_FORMATS`.
I will use another example. Actually some of these tests are for files that are not found.

File: src/test/java/reposense/git/GitLogTest.java [hunk 27]
```diff
@@ -64,17 +64,68 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("**Test**"));
+        content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(5, content));
+
+        // Files that do not exist
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("**blameTest"));
+        content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(7, content));
+
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("nonExisting.txt"));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: this one i think can use `README.md`?

File: src/test/java/reposense/git/GitLogTest.java [hunk 28]
```diff
@@ -64,17 +64,68 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+        content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(7, content));
+
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("./java"));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: this can use any value file, prefix with the `./` to demonstrate that it is valid and working.
e.g. `./newPos` to show the clear difference between this and the invalid example

File: src/test/java/reposense/git/GitLogTest.java [hunk 29]
```diff
@@ -64,17 +64,68 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+        content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(7, content));
+
+    }
+
+    @Test
+    public void gitLog_authorIgnoreInvalidFilePath_success() {
+        config.setFormats(Collections.singletonList(new Format("java")));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: do remove this so that the result is visually comparable from the other test.

File: src/test/java/reposense/git/GitLogTest.java [hunk 30]
```diff
@@ -64,17 +64,68 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("annotationTest.java"));
+        String content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(6, content));
+
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("**Test**"));
+        content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(5, content));
+
+        // Files that do not exist
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("**blameTest"));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: I think this can just use `**.java` or something.

File: src/test/java/reposense/git/GitLogTest.java [hunk 31]
```diff
@@ -64,17 +64,68 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
         ignoreAllJavaFilesAuthor.setIgnoreGlobList(Collections.singletonList("*.java"));
 
-        String content = GitLog.get(config, ignoreAllJavaFilesAuthor);
-        Assert.assertTrue(TestUtil.compareNumberExpectedCommitsToGitLogLines(2, content));
+        String content = GitLog.getWithFiles(config, ignoreAllJavaFilesAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(0, content));
+    }
+
+    @Test
+    public void gitLog_authorIgnoreValidFilePath_success() {
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: Sorry, i didn't identify this earlier.
`authorIgnoreValidFilePath` -> `validIgnoreGlobs`.

The author can be removed since this applies to the global ignore glob as well.

File: src/test/java/reposense/git/GitLogTest.java [hunk 32]
```diff
@@ -64,17 +64,68 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+        Author ignoreValidFileAuthor = getAlphaAllAliasAuthor();
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: can just name it `author` since this is not a specially created author for this test.

File: src/test/java/reposense/git/GitLogTest.java [hunk 33]
```diff
@@ -64,17 +64,68 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(7, content));
+
+        ignoreValidFileAuthor.setIgnoreGlobList(Collections.singletonList("./java"));
+        content = GitLog.getWithFiles(config, ignoreValidFileAuthor);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(7, content));
+
+    }
+
+    @Test
+    public void gitLog_authorIgnoreInvalidFilePath_success() {
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: similarly, here should be `gitLog_invalidIgnoreGlobs_filtered`

File: src/test/java/reposense/git/GitLogTest.java [hunk 34]
```diff
@@ -64,17 +64,68 @@ public void gitLog_includeAllJavaFilesAuthorIgnoreMovedFile_success() {
...
+        config.setFormats(Collections.singletonList(new Format("java")));
+        Author ignoreInvalidFileAuthor = getAlphaAllAliasAuthor();
+
+        ignoreInvalidFileAuthor.setIgnoreGlobList(Collections.singletonList("../bin"));
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: make this `../testrepo-Alpha` because thats the folder name when u cloned the repo

**Comment by eugenepeh** [comment]
just add 1 non existence glob for the success case will do.

File: src/test/java/reposense/git/GitLogTest.java [hunk 35]
```diff
@@ -79,53 +79,50 @@ public void gitLog_authorIgnoreAllJavaFiles_success() {
...
+        content = GitLog.getWithFiles(config, author);
+        Assert.assertTrue(TestUtil.compareNumberFilesChanged(6, content));
 
     }
 
     @Test
-    public void gitLog_authorIgnoreInvalidFilePath_success() {
-        config.setFormats(Collections.singletonList(new Format("java")));
-        Author ignoreInvalidFileAuthor = getAlphaAllAliasAuthor();
+    public void gitLog_invalidIgnoreGlobs_success() {
```
Comment (eugenepeh) [inline src/test/java/reposense/git/GitLogTest.java]: last word should be filtered, because thats the expected behavior

`gitLog_invalidIgnoreGlobs_filtered`

**Comment by yamidark** [comment]
Slights nits to proposed message:
```
If users try to put folders existing outside of the git repository 
inside the ignore-glob-list, it will lead to a RuntimeException as the
`git log` command fails.

Let's check that the path is inside the repository, before writing it
into the ignore-glob-list and running the `git log` command.
```
