### PR TITLE
[#825] Zip: fix invalid report file directories being zipped

### LINKED ISSUE #806: Add checks to ensure that report folders and files are successfully generated before attempting to zip them
This issue can be attempted after PR #656 is merged.

Issue: The method `generateReposReport` returns a list of file paths to authorship and commits json files for each repo **and assumes that these folders and files already exist**. 

Solution: returns a list of file paths to authorship and commits json files for each repo **after ensuring that these folders and files already exist**.

> Still not really the ideal solution because this assumes that the files were generated which might not be the case, but we can settle that in another issue.
> 
> The ideal solution should the methods, that generate the file e.g. FileUtil.writeJsonFile, return the path of the files that were successfully generated. Only then, `generateReposReport` should consolidate them one by one and return it to the caller.
> 
> _Originally posted by @eugenepeh in https://github.com/reposense/RepoSense/pull/656_

### LINKED ISSUE #825: Weird log message that displays report location of a certain repo with no reason for the error
Parameters used: `-c ./ -s d1 -v`

Weird line of log is displayed as error: 
```
10:13:35 - [ERROR] C:\Users\jylee\Documents\repos\RepoSense\reposense-report\reposense\testrepo-Alpha[master]
```
, located at the 4th last line of the log below.

The full log is displayed below.

```
10:11:48 - Cloning in parallel from https://github.com/reposense/testrepo-Delta.git...
10:11:48 - Waiting for cloning of https://github.com/reposense/testrepo-Delta.git to complete...
10:11:54 - Cloning of https://github.com/reposense/testrepo-Delta.git completed!
10:12:00 - Cloning in parallel from https://github.com/reposense/RepoSense.git...
10:12:00 - Analyzing https://github.com/reposense/testrepo-Delta.git (master)...
10:12:01 - Extracting commits info for https://github.com/reposense/testrepo-Delta.git (master)...
10:12:02 - Analyzing commits info for https://github.com/reposense/testrepo-Delta.git (master)...
10:12:02 - Extracting relevant file info from https://github.com/reposense/testrepo-Delta.git (master)...
10:12:41 - Analysis of https://github.com/reposense/testrepo-Delta.git (master) completed!
10:12:41 - Analyzing https://github.com/reposense/testrepo-Delta.git (nonExistentBranch)...
10:12:41 - [ERROR] Branch nonExistentBranch does not exist in https://github.com/reposense/testrepo-Delta.git! Analysis terminated.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/C:/Users/jylee/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.5/f645ed69d595b24d4cf8b3fbb64cc505bede8829/gson-2.8.5.jar) to constructor java.util.Collections$EmptyList()
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:12:41 - Waiting for cloning of https://github.com/reposense/RepoSense.git to complete...
10:12:41 - Cloning of https://github.com/reposense/RepoSense.git completed!
10:12:46 - Cloning in parallel from https://github.com/reposense/testrepo-Alpha.git...
10:12:46 - Analyzing https://github.com/reposense/RepoSense.git (master)...
10:12:46 - Extracting commits info for https://github.com/reposense/RepoSense.git (master)...
10:12:47 - Analyzing commits info for https://github.com/reposense/RepoSense.git (master)...
10:12:47 - Extracting relevant file info from https://github.com/reposense/RepoSense.git (master)...
10:13:02 - Analysis of https://github.com/reposense/RepoSense.git (master) completed!
10:13:02 - Waiting for cloning of https://github.com/reposense/testrepo-Alpha.git to complete...
10:13:02 - Cloning of https://github.com/reposense/testrepo-Alpha.git completed!
reposense.git.exception.GitCloneException: reposense.system.CommandRunnerProcessException: Error returned from command git ls-tree --name-only -r masteron path repos\reposense_testrepo-Empty\testrepo-Empty :
fatal: Not a valid object name master

	at reposense.git.GitLsTree.validateFilePaths(GitLsTree.java:54)
	at reposense.report.RepoCloner.spawnCloneProcess(RepoCloner.java:104)
	at reposense.report.RepoCloner.clone(RepoCloner.java:56)
	at reposense.report.ReportGenerator.cloneAndAnalyzeRepos(ReportGenerator.java:128)
	at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:82)
	at reposense.RepoSense.main(RepoSense.java:61)
10:13:04 - Analyzing https://github.com/reposense/testrepo-Alpha.git (master)...
10:13:04 - [WARNING] The provided commit hash, , contains illegal characters. Ignoring the config provided by https://github.com/reposense/testrepo-Alpha.git (master).
10:13:04 - https://github.com/reposense/testrepo-Alpha.git (master) has no authors specified, using all authors by default.
10:13:04 - Extracting commits info for https://github.com/reposense/testrepo-Alpha.git (master)...
10:13:05 - Analyzing commits info for https://github.com/reposense/testrepo-Alpha.git (master)...
10:13:05 - Extracting relevant file info from https://github.com/reposense/testrepo-Alpha.git (master)...
10:13:06 - Analysis of https://github.com/reposense/testrepo-Alpha.git (master) completed!
10:13:06 - Waiting for cloning of https://github.com/reposense/testrepo-Empty.git to complete...
10:13:06 - [WARNING] Exception met while trying to clone the repo, will skip this repo.
10:13:14 - Cloning in parallel from https://github.com/reposense/testrepo-Beta.git...
10:13:14 - Waiting for cloning of https://github.com/reposense/testrepo-Beta.git to complete...
10:13:26 - Cloning of https://github.com/reposense/testrepo-Beta.git completed!
10:13:27 - Analyzing https://github.com/reposense/testrepo-Beta.git (master)...
10:13:27 - Ignoring standalone config file in https://github.com/reposense/testrepo-Beta.git (master).
10:13:27 - Extracting commits info for https://github.com/reposense/testrepo-Beta.git (master)...
10:13:28 - Analyzing commits info for https://github.com/reposense/testrepo-Beta.git (master)...
10:13:28 - Extracting relevant file info from https://github.com/reposense/testrepo-Beta.git (master)...
10:13:31 - Analysis of https://github.com/reposense/testrepo-Beta.git (master) completed!
10:13:31 - Analyzing https://github.com/reposense/testrepo-Beta.git (add-config-json)...
10:13:31 - Ignoring standalone config file in https://github.com/reposense/testrepo-Beta.git (add-config-json).
10:13:31 - Extracting commits info for https://github.com/reposense/testrepo-Beta.git (add-config-json)...
10:13:32 - Analyzing commits info for https://github.com/reposense/testrepo-Beta.git (add-config-json)...
10:13:32 - Extracting relevant file info from https://github.com/reposense/testrepo-Beta.git (add-config-json)...
10:13:35 - Analysis of https://github.com/reposense/testrepo-Beta.git (add-config-json) completed!
10:13:35 - The report is generated at C:\Users\jylee\Documents\repos\RepoSense\reposense-report
10:13:35 - [ERROR] C:\Users\jylee\Documents\repos\RepoSense\reposense-report\reposense\testrepo-Alpha[master]
10:13:35 - Starting a server at port 9000...
10:13:35 - Loading http://localhost:9000/ on the default browser...
10:13:35 - Press Ctrl + C or equivalent to stop the server

```

### PR DESCRIPTION
**Pull request by jylee-git**
```
Due to a change in the RepoConfiguration display name in a recent PR, 
the ZIP utility now attempts to zip report folders using the new 
display name. Hence, the name of the report folder is now different 
from the display name, which results in none of the files being zipped,
and not being able to display the report on the dashboard.

Let's use the output folder name instead of the repo display name so 
that the report files can be zipped successfully.
```

Fixes #825

### CODE REVIEW

**Comment by jylee-git** [comment]
@eugenepeh 

> The ideal solution should the methods, that generate the file e.g. FileUtil.writeJsonFile, return the path of the files that were successfully generated. Only then, `generateReposReport` should consolidate them one by one and return it to the caller.
> 
> _Originally posted by @eugenepeh in https://github.com/reposense/RepoSense/pull/656_

Would this alternative be better?
Validate (that the files exist) and consolidate the respective report files to a list and return it only after analyzing all repos.

This solution is already reflected in this PR.

**Comment by eugenepeh** [comment]
>This alternative is already reflected in this PR.

No, current implementation is still bad; it doesn't seems any different from previous implementation. 
What you're doing now is similar to checking your entire inventory after making the purchase, and that is kind of doing double the work.

To avoid too many redundant code, you should be taking note of the items as `it goes through the scanner` / `directly after it went into the `bag`. This should be done at a lower level, e.g. `FileUtil.writeJsonFile` where it returns the FilePath when it has successfully written the json file.

**Comment by jylee-git** [comment]
> No, current implementation is still bad; it doesn't seems any different from previous implementation.
> What you're doing now is similar to checking your entire inventory after making the purchase, and that is kind of doing double the work.
> 
> To avoid too many redundant code, you should be taking note of the items as `it goes through the scanner` / `directly after it went into the bag`. This should be done at a lower level, e.g. `FileUtil.writeJsonFile` where it returns the FilePath after it has successfully written the json file.

Can the resulting list of generated report files be a private global variable in `ReportGenerator` class? Because if not, we will need to modify methods from outside `ReportGenerator` class just to return a list of generated report files, resulting in lots of redundant code.

With this, we can just add the generated files to the list (while on the go).

**Comment by eugenepeh** [comment]
>Can the resulting list of generated report files be a private global variable in ReportGenerator class? Because if not, we will need to modify methods from outside ReportGenerator class just to return a list of generated report files, resulting in lots of redundant code.

I see. That's fine since its out of the scope for this PR. Do help me open another issue to highlight this problem because its a implementation problem.

**Comment by jylee-git** [comment]
> > Can the resulting list of generated report files be a private global variable in ReportGenerator class? Because if not, we will need to modify methods from outside ReportGenerator class just to return a list of generated report files, resulting in lots of redundant code.
> 
> I see. That's fine since its out of the scope for this PR. Do help me open another issue to highlight this design problem.

Ok. But should we still implement the checking of existing files and use global variables? Or should we axe the checking of files for now and just fix #825 because the zipping functionality is broken and needs to be dealt with ASAP

**Comment by eugenepeh** [comment]
>But should we still implement the checking of existing files and use global variables?

I thought this implementation was to not accidentally zip files that were not generated by the program? In that case, we dont need to check for existing files.

**Comment by jylee-git** [comment]
> But should we still implement the checking of existing files and use global variables?

Sorry, my comment wasn't clear enough as it was pretty late at night.. But what I meant was should we still intend to implement whether to add the list of generated files into the static variable to be returned and parsed into the zip method, given the current state of the design implementation.


> I thought this implementation was to not accidentally zip files that were not generated by the program? In that case, we dont need to check for existing files.

This is actually solving the issue by adding only files generated by the program (iff `writeJson` successfully into the JSON file without any exception being thrown and returns the path of the file) to the `private static List<Path> generatedReportFiles`, then to be parsed into `zipFoldersAndFiles`.

**Comment by eugenepeh** [comment]
>This is actually solving the issue by adding only files generated by the program (iff writeJson successfully into the JSON file without any exception being thrown and returns the path of the file) to the private static List<Path> generatedReportFiles, then to be parsed into zipFoldersAndFiles.

Current implementation is good enough for me with regards to the fix to zip. 

>Fix ssues with files not being able to zip due to the change in repo folder display name, and

This can be tackled in another PR.

>Add only files successfully generated by the JSON files to the private static List<Path> generatedReportFiles to be returned and parsed into the ZIP util

Isn't this what is being done above? 

The complete solution should actually be not to use global variable; the files that were generated should come in a smooth flow into the generatedReportFiles and be returned itself.
This can be done in another PR.

**Comment by jylee-git** [comment]
> The complete solution should actually be not to use global variable; the files that were generated should come in a smooth flow into the generatedReportFiles and be returned itself.
> This can be done in another PR.

Ok, so with regards to this: since it's the current design implementation problem that dosen't allow us to use non-global variables without adding too many redundant codes, here's what I'll do: -
- Raise an issue to highlight the current implementation problem and have someone to refactor the code base to:
  -  Ensure that files that are successfully generated and written by `writeJson` method gets taken note of and returned from the `generateReposReport` method without having to use a global variable
- Make this PR only to deal with the incorrect directory names being parsed into the ZIP util

File: src/main/java/reposense/util/FileUtil.java [hunk 1]
```diff
@@ -40,6 +40,8 @@
     private static final ByteBuffer buffer = ByteBuffer.allocate(1 << 11); // 2KB
 
     private static final String MESSAGE_INVALID_FILE_PATH = "\"%s\" is an invalid file path. Skipping this directory.";
+    private static final String MESSAGE_FAIL_TO_ZIP_FILES =
+            "Exception occurred while attempting to ZIP the contents of the report files.";
```
Comment (fzdy1914) [inline src/main/java/reposense/util/FileUtil.java]: My idea: `Exception occurred while attempting to ZIP the report files.` is enough.

File: src/main/java/reposense/util/FileUtil.java [hunk 2]
```diff
@@ -40,6 +40,8 @@
     private static final ByteBuffer buffer = ByteBuffer.allocate(1 << 11); // 2KB
 
     private static final String MESSAGE_INVALID_FILE_PATH = "\"%s\" is an invalid file path. Skipping this directory.";
+    private static final String MESSAGE_FAIL_TO_ZIP_FILES =
+            "Exception occurred while attempting to ZIP the report files.";
```
Comment (yong24s) [inline src/main/java/reposense/util/FileUtil.java]: `ZIP` -> `zip`.

Also, instead of saying `Exception occurred`, perhaps state that the report files are missing or corrupted?

Comment (jylee-git) [reply src/main/java/reposense/util/FileUtil.java]: > Also, instead of saying Exception occurred, perhaps state that the report files are missing or corrupted?

I don't think we should narrow down to `report files are missing or corrupted` as many reasons can happen that it failed to zip. 

For example in this PR, the reason is due to the invalid directory being parsed in, but doesn't mean that the report files are missing or corrupted.

**Comment by eugenepeh** [comment]
Nits to proposed message:

```
Due to a change in the RepoConfiguration display name in a recent PR, 
the ZIP utility now attempts to zip report folders using the new 
display name. Hence, as the name of the report folder is now different 
from the display name, this results in none of the files being zipped
and produce a zip file unusable to display the report.

Let's fix this by directing the zip algorithm to look for the
`OutputFolderName` instead.
```

**Comment by jylee-git** [comment]
> Nits to proposed message:
> 
> ```
> Due to a change in the RepoConfiguration display name in a recent PR,
> #802, the ZIP utility now attempts to zip report folders using the new 
> display name. Hence, as the name of the report folder is now different 
> from the display name, this results in none of the files being zipped
> and produce a zip file unusable to display the report.
> 
> Let's fix this by directing the zip algorithm to look for the
> `OutputFolderName` instead.
> ```

Noted. Thanks for the feedback
