### PR TITLE
[#1333] Fix loading of local reports

### LINKED ISSUE #1333: Locally ran report loads infinitely
**Tell us about your environment**

* **RepoSense Version:**
Master branch

* **OS and Version:**
MacOS Catalina 10.15.7

* **Web Browser and Version (if applicable):**
Chrome

**Please include the steps to reproduce the bug.**

1. Run a reposense analysis locally
2. Open the report, report loads infinitely

**What was expected to happen?**
Report should finish loading after awhile.

**What actually happened? Please include a screenshot of the output.**
The loading page loads infinitely.
Screen Shot 2020-09-29 at 8 15 21 PM

I suspect where it is due to the current code, where it is trying to call `startsWith` with `version` that is undefined.
Screen Shot 2020-09-29 at 8 15 50 PM

**If possible, include the URL to your RepoSense report or log files (if any).**
N.A.

### PR DESCRIPTION
**Pull request by Tejas2805**
Fixes #1333 

```
The loading page is loading infinitely. This is because it is trying to call 
`startsWith` with `version` that is undefined.

Let's fix it by adding a check to see if `version` is undefined or not. 
```

### CODE REVIEW

**Comment by Tejas2805** [comment]
@jamessspanggg I think the problem should be fixed. Can try locally once.

File: frontend/src/static/js/main.js [hunk 1]
```diff
@@ -188,14 +188,17 @@ window.app = new window.Vue({
...
+        return `${window.HOME_PAGE_URL}/RepoSense/`;
       }
-      return `${window.HOME_PAGE_URL}/RepoSense/`;
+      return `${window.HOME_PAGE_URL}`;
     },
 
     getSpecificCommitLink() {
       const version = window.app.repoSenseVersion;
+      if (!version) {
+        return `${window.BASE_URL}reposense/RepoSense`;
```
Comment (jamessspanggg) [inline frontend/src/static/js/main.js:200]: missing a `/` here

**Review by jamessspanggg — CHANGES_REQUESTED** [review]

**Review by jamessspanggg — APPROVED** [review]

**Review by fzdy1914 — APPROVED** [review]
