### PR TITLE
[#1129] RepoSense: exit gracefully when all repo locations are invalid

### LINKED ISSUE #1129: RepoSense crashes too late if there are 0 valid locations in `--repo` argument
To replicate, run the command:
`./gradlew run -Dargs="--repo abc.git"`

Output:
```
01:51:34 - [WARNING] abc.git is an invalid location.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at reposense.report.ReportGenerator.cloneAndAnalyzeRepos(ReportGenerator.java:153)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:98)
        at reposense.RepoSense.main(RepoSense.java:69)
```

As seen in the stack trace, RepoSense tries to proceed with report generation even though there are no valid repo locations.

Expected: RepoSense should not proceed with report generation if there are no valid locations.

To solve: Check that there is at least one valid location

### PR DESCRIPTION
**Pull request by shuiyao-sg**
Fixes #1129 
```
RepoSense invokes ReportGenerator.generateReposReport()
even if all repository locations in the arguments are invalid.

This is due to the try-catch block in
RepoSense.getRepoConfigurations(), which prevents the
InvalidLocationException to be thrown and interrupt
the execution of the program. Therefore, RepoSense cannot abort early
when all repository locations are invalid.

Let's add one more condition check before return, such that
an exception will be thrown if the RepoConfiguration list is empty.
The empty RepoConfiguration list suggests that all repository
locations are invalid and hence nothing is added to the list.
```

### CODE REVIEW

**Comment by Tejas2805** [comment]
Hey,

Thank you for your contribution to RepoSense. Please follow our [contributor guidelines](https://github.com/reposense/RepoSense/blob/master/docs/Process.md#how-to-contribute-to-the-reposense-repository) and accordingly update your commit message.

**Comment by shuiyao-sg** [comment]
> Hey,
> 
> Thank you for your contribution to RepoSense. Please follow our [contributor guidelines](https://github.com/reposense/RepoSense/blob/master/docs/Process.md#how-to-contribute-to-the-reposense-repository) and accordingly update your commit message.

Is there anything else that needs to be changed besides commit message?

**Comment by 0blivious** [comment]
Thx for the contribution. Pls manage your commits properly, there seems to be a lot of irrelevant commits in your PR. Also, ensure you pass the CIs  before requesting for review.

**Comment by shuiyao-sg** [comment]
> Thx for the contribution. Pls manage your commits properly, there seems to be a lot of irrelevant commits in your PR. Also, ensure you pass the CIs before requesting for review.

The irrelavent commits appeared when I used `git rebase` to refactor my commit message. I'm trying to fix it. Also, when I pulled from `master` to sync my code, it then cannot pass the CI tests.

**Comment by shuiyao-sg** [comment]
May I know if there is a guide on how to set up these CI checks in my own fork? so that I can ensure I pass the checks before I open the PR?

**Comment by jamessspanggg** [comment]
> May I know if there is a guide on how to set up these CI checks in my own fork? so that I can ensure I pass the checks before I open the PR?

Hi, there isn't a current documented guide to set up these CI checks in your own fork. To set up the CI checks in your own fork, you just have to enable travis etc in ur forked repo.

Another alternative is to make a draft PR, which will let us know that the PR isn't ready yet. More details: [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

**Comment by anubh-v** [comment]
> May I know if there is a guide on how to set up these CI checks in my own fork? so that I can ensure I pass the checks before I open the PR?

Another option is to run the checks locally on your computer.
You can use the following commands for checks related to the Java code:
- `./gradlew test` (unit and integration tests under `src/test`)
- `./gradlew systemtests` (system tests under `src/systemtest`)
- `./gradlew checkstyleMain` / `./gradlew checkstyleTest` / `./gradlew checkstyleSystemtest` (to run CheckStyle on the main project, test or system test code respectively)

Tests can also be run from your IDE.

**Comment by shuiyao-sg** [comment]
Thank you guys for you suggestions!

File: src/main/java/reposense/RepoSense.java [hunk 1]
```diff
@@ -126,16 +126,12 @@ public static void main(String[] args) {
     /**
      * Constructs a list of {@code RepoConfiguration} if {@code cliArguments} is a {@code LocationsCliArguments}.
      */
-    public static List<RepoConfiguration> getRepoConfigurations(LocationsCliArguments cliArguments) {
+    public static List<RepoConfiguration> getRepoConfigurations(LocationsCliArguments cliArguments)
+            throws InvalidLocationException {
         List<RepoConfiguration> configs = new ArrayList<>();
         for (String locationString : cliArguments.getLocations()) {
-            try {
```
Comment (anubh-v) [inline src/main/java/reposense/RepoSense.java]: Thanks for making this contribution!
Removing the try-catch block may not be the most appropriate solution.
I think it'll be helpful if I provide a bit more background so the approach can be improved.
- The `--repo` parameter can accept  multiple repository locations:
  Example: 
`java -jar RepoSense.jar --repo https://github.com/reposense/RepoSense.git https://github.com/se-edu/addressbook-level4.git`
- We would not want to abort RepoSense entirely if only some repository locations are invalid. For example, if the command was `java -jar RepoSense.jar --repo abc.git https://github.com/se-edu/addressbook-level4.git`, then we still want RepoSense to analyse the AddressBook Level 4 repository. RepoSense should continue execution as long as there is a non zero number of valid repository locations. The invalid repository locations can be ignored.

- Currently, we using a logger to emit a warning if any repository location is invalid (line 135 in `RepoSense.java`)

Removing the try-catch block entirely may not be the most appropriate solution as this aborts RepoSense even if there is only one invalid repository location.

Comment (shuiyao-sg) [reply src/main/java/reposense/RepoSense.java]: Thank you for your clarification! So does it mean we need abort RepoSense only if there is one repo location AND the location is invalid?

What is the expected behaviour if there is no argument of location after `--repo`? For example: `java -jar RepoSense.jar --repo`

Comment (anubh-v) [reply src/main/java/reposense/RepoSense.java]: > What is the expected behaviour if there is no argument of location after --repo?

RepoSense is able to detect if 0 locations are provided. A `ParseException` will be thrown and RepoSense will terminate. You can look at the `ArgParser` class to see how the command line arguments are interpreted.

> So does it mean we need abort RepoSense only if there is one repo location AND the location is invalid?

We need to abort RepoSense if all the repo locations are invalid.
Example: If 5 repo locations are provided, and all 5 are invalid, then RepoSense should terminate.
If 5 repo locations are provided, and 4 are invalid, then RepoSense should ignore the 4 invalid locations and proceed to analyze the 1 valid repository.

Comment (shuiyao-sg) [reply src/main/java/reposense/RepoSense.java]: Sure. Thank you so much! I'll try to figure it out.

File: src/test/java/reposense/parser/ArgsParserTest.java [hunk 2]
```diff
@@ -462,14 +462,13 @@ public void parse_repoAliases_sameResult() throws ParseException, HelpScreenExce
         Assert.assertEquals(repoAliasCliArguments, reposAliasCliArguments);
     }
 
-    @Test
-    public void parse_invalidRepoLocation_emptyRepoConfigurationList()
+    @Test (expected = InvalidLocationException.class)
```
Comment (shuiyao-sg) [inline src/test/java/reposense/parser/ArgsParserTest.java]: I modified the test to expect an exception thrown instead of testing for empty `repoConfigs` list. I guess it's this method causing the `codecov` check to fail? But I'm not sure where does the `-<0.1%` come from. May I know how I should figure it out and fix this?

File: src/main/java/reposense/RepoSense.java [hunk 3]
```diff
@@ -136,6 +139,10 @@ public static void main(String[] args) {
             }
         }
 
+        if (configs.isEmpty()) {
+            throw new InvalidLocationException("All locations are invalid. Please supply at least one valid location.");
```
Comment (anubh-v) [inline src/main/java/reposense/RepoSense.java]: I think we can change the message to just `All repository locations are invalid`.
`repository locations` is a little clearer than `locations`.
We can omit the sentence `Please supply at least one valid location.` as it's self explanatory.

File: src/test/java/reposense/parser/ArgsParserTest.java (hunk 2 above)
Comment (anubh-v) [reply src/test/java/reposense/parser/ArgsParserTest.java]: It is ok. Extremely small fluctuations in the code coverage may not be meaningful.

File: src/main/java/reposense/RepoSense.java (hunk 3 above)
Comment (shuiyao-sg) [reply src/main/java/reposense/RepoSense.java]: Sure! I'll make the changes right now. Then do I need to do anything to pass the `codecov` check? cos I'm a bit confused with it

**Comment by anubh-v** [comment]
@shuiyao-sg, could you update your commit message in line with the new approach?
Take a look at [this PR](https://github.com/reposense/RepoSense/pull/1141) to see an example on how to format the commit message

**Comment by anubh-v** [comment]
@shuiyao-sg, do update your title as well.
The naming conventions for PR titles are [here](https://oss-generic.github.io/process/docs/FormatsAndConventions.html#pr)

**Comment by jamessspanggg** [comment]
@anubh-v would this issue also occur there's invalid repo locations in the `repo-config.csv`?

**Comment by anubh-v** [comment]
> would this issue also occur there's invalid repo locations in the repo-config.csv?

@jamessspanggg, it will not occur.
RepoSense will terminate if all repo locations in `repo-config.csv` are invalid.
This is verified by `RepoConfigCsvParser`

**Comment by shuiyao-sg** [comment]
> @shuiyao-sg, could you update your commit message in line with the new approach?
> Take a look at [this PR](https://github.com/reposense/RepoSense/pull/1141) to see an example on how to format the commit message

@anubh-v  Thank you for your comment! May I clarify that do I need to make each commit message into one sentence as what [this PR](https://github.com/reposense/RepoSense/pull/1141) did? And do I need to refactor all the commits or just the last commit?

Also, previously I've followed [this advice](https://stackoverflow.com/questions/1186535/how-to-modify-a-specified-commit/1186549#1186549) on refactoring commit using `git rebase`. But after that I cannot push to Github and I used `git push --force`, which messed up my commit history with some irrelevant commits. May I know is there a better way to refactor commit / commit message?

**Comment by jamessspanggg** [comment]
> May I clarify that do I need to make each commit message into one sentence as what [this PR](https://github.com/reposense/RepoSense/pull/1141) did? 

Not for each commit message, but only for your PR message. Note that the PR message should be wrapped within a code segment. You can refer to the PR that you referenced.

**Comment by shuiyao-sg** [comment]
> > May I clarify that do I need to make each commit message into one sentence as what [this PR](https://github.com/reposense/RepoSense/pull/1141) did?
> 
> Not for each commit message, but only for your PR message. Note that the PR message should be wrapped within a code segment. You can refer to the PR that you referenced.

OK, I'll figure it out. Just to confirm, so there are three things I need to do:
1. Modify the exception message for the `InvalidLocationException` thrown in `RepoSense.getRepoConfigurations()`
2. Modify the PR message
3. Modify the PR title

Is that correct?

**Comment by anubh-v** [comment]
> OK, I'll figure it out. Just to confirm, so there are three things I need to do:
> 
>     1. Modify the exception message for the `InvalidLocationException` thrown in `RepoSense.getRepoConfigurations()`
> 
>     2. Modify the PR message
> 
>     3. Modify the PR title
> 
> 
> Is that correct?

Yes. Thanks for the contribution.

File: src/main/java/reposense/RepoSense.java (hunk 3 above)
Comment (anubh-v) [reply src/main/java/reposense/RepoSense.java]: > Then do I need to do anything to pass the codecov check?

No further work needed for this.
In general, extremely small changes to code coverage may not be meaningful.

Comment (shuiyao-sg) [reply src/main/java/reposense/RepoSense.java]: Sure! Thank you for clarification!

**Comment by shuiyao-sg** [comment]
> LGTM, just one more nit on the commit message:
> 
> Screen Shot 2020-03-20 at 12 21 41 AM

Thank you for your comment, I'll fix it now.

File: src/test/java/reposense/parser/ArgsParserTest.java [hunk 4]
```diff
@@ -462,14 +462,13 @@ public void parse_repoAliases_sameResult() throws ParseException, HelpScreenExce
...
+    public void parse_invalidRepoLocation_throwsInvalidLocationException()
```
Comment (jylee-git) [inline src/test/java/reposense/parser/ArgsParserTest.java]: `RepoSense.getRepoConfigurations` throws  invalidLocException only when there are no valid repo locations provided right (regardless of the number of "RepoLocations" being thrown in)?

 If so, perhaps the test name can be changed to something like `parse_noValidRepoLocation_throws...()`.

Comment (shuiyao-sg) [reply src/test/java/reposense/parser/ArgsParserTest.java]: sure

Comment (shuiyao-sg) [reply src/test/java/reposense/parser/ArgsParserTest.java]: Yes `RepoSense.getRepoConfigurations` throws invalidLocationException only when no valid locations provided AND the number of repolocations in argument >= 1. If no repo location supplied at all, it will be handled by ArgsParser at an earlier stage.

File: src/test/java/reposense/parser/ArgsParserTest.java (hunk 2 above)
Comment (Tejas2805) [reply src/test/java/reposense/parser/ArgsParserTest.java]: I believe this is due to the extra condition added and no test case covering it.

Comment (fzdy1914) [inline src/test/java/reposense/parser/ArgsParserTest.java]: Even the logic is correct, this test should be in a different location though. This test is mean to test `ArgsParser`. Lets maintain this original test and add this test elsewhere.

File: src/main/java/reposense/RepoSense.java [hunk 5]
```diff
@@ -126,8 +126,11 @@ public static void main(String[] args) {
 
     /**
      * Constructs a list of {@code RepoConfiguration} if {@code cliArguments} is a {@code LocationsCliArguments}.
+     *
+     * @throws InvalidLocationException if all repo locations are invalid.
```
Comment (fzdy1914) [inline src/main/java/reposense/RepoSense.java]: It is not so ideal to use `InvalidLoactionException`. However, it is still acceptable.

Comment (shuiyao-sg) [reply src/main/java/reposense/RepoSense.java]: Thank you for your suggestion! So should I implement another exception class to handle this?

File: src/test/java/reposense/parser/ArgsParserTest.java (hunk 2 above)
Comment (shuiyao-sg) [reply src/test/java/reposense/parser/ArgsParserTest.java]: Thank you for your suggestion! I'll fix this by tomorrow.

Comment (shuiyao-sg) [reply src/test/java/reposense/parser/ArgsParserTest.java]: Thank you for clarifying!

File: src/main/java/reposense/RepoSense.java (hunk 5 above)
Comment (anubh-v) [reply src/main/java/reposense/RepoSense.java]: I think `ParseException` will be suitable?

Comment (shuiyao-sg) [reply src/main/java/reposense/RepoSense.java]: sure

File: src/test/java/reposense/parser/ArgsParserTest.java (hunk 2 above)
Comment (shuiyao-sg) [reply src/test/java/reposense/parser/ArgsParserTest.java]: The original test was testing for the same component as the modified test. Basically they are both testing for the scenario where all repo locations supplied in the argument are invalid. The only change I made was the expected behaviour. The original test was verifying that the repo configuaration list is empty in method `RepoSense.getRepoConfigurations()` if all repo locations are invalid. I modified the method to make it throw exception when all locations are invalid. Therefore I also modified the test to expect an exception thrown. Since the test was in `ArgsParserTest.java` before I started to work on this component, I'm assuming that the development team decided to put it and treat it as something related to parsing user arguments. In this case, do I still need to move the test to somewhere else?

Comment (anubh-v) [reply src/test/java/reposense/parser/ArgsParserTest.java:465]: I think @shuiyao-sg 's modification to the test is correct, but perhaps this test should not be in `ArgsParserTest`.

Majority of the tests in `ArgsParserTest` are testing whether the `CliArguments` object is correctly created by `ArgsParser`. However, this test seems to be checking the logic in RepoSense's driver class (i.e. `RepoSense.java`).

I think it should be moved into a separate file where we can test the logic in RepoSense's driver class.
However, perhaps this can be done in a subsequent PR, and this PR can proceed first?

I have created an issue on moving this tests [here](https://github.com/reposense/RepoSense/issues/1234)

Comment (anubh-v) [reply src/test/java/reposense/parser/ArgsParserTest.java:465]: @eugenepeh, may we get your advice here?

I think that @shuiyao-sg 's modification to the test `parse_noValidRepoLocation_throwsInvalidLocationException` is appropriate.

However, I think this test should moved to a new test file, as I've explained above.
I think this PR can be merged first, and we can move the test in another PR?

File: src/main/java/reposense/RepoSense.java (hunk 5 above)
Comment (anubh-v) [reply src/main/java/reposense/RepoSense.java:130]: @shuiyao-sg, could you update the exception? Thanks!

Comment (shuiyao-sg) [reply src/main/java/reposense/RepoSense.java:130]: sure, I'll update it now.

File: src/test/java/reposense/parser/ArgsParserTest.java (hunk 2 above)
Comment (anubh-v) [reply src/test/java/reposense/parser/ArgsParserTest.java]: @fzdy1914 may we get your input on this discussion?

Comment (anubh-v) [reply src/test/java/reposense/parser/ArgsParserTest.java]: @fzdy1914 may we get your thoughts when you are free? Thanks!

Comment (fzdy1914) [reply src/test/java/reposense/parser/ArgsParserTest.java]: Sorry for not replying, I think your suggestion is fine.

**Comment by fzdy1914** [comment]
@shuiyao-sg Sorry for your long wait, can you help resolve the conflicts?

**Comment by shuiyao-sg** [comment]
@fzdy1914 I'm sorry that I just saw this comment. I'll resolve the conflicts during this weekend.

**Comment by anubh-v** [comment]
@fzdy1914 the conflicts have been resolved

File: src/main/java/reposense/RepoSense.java (hunk 5 above)
Comment (fzdy1914) [inline src/main/java/reposense/RepoSense.java:130]: Can help change the name of the doc? It is not correct now.

Comment (shuiyao-sg) [reply src/main/java/reposense/RepoSense.java]: Sure. Name changed in the new commit.
