### PR TITLE
[#561] DashboardServer: Desktop#isDesktopSupported passes on headless systems

### LINKED ISSUE #561: DashboardServer: Desktop#isDesktopSupported passes on headless systems
https://github.com/reposense/RepoSense/blob/2c6b44ac323008c3c2b55789fee9c2f014c2f879/src/main/java/reposense/system/DashboardServer.java#L48-L50

```
> Task :startServerInBackground
** (java:5160): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Exception in thread "main" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
    at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
    at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
    at reposense.system.DashboardServer.launchBrowser(DashboardServer.java:49)
    at reposense.system.DashboardServer.startServer(DashboardServer.java:36)
    at reposense.RepoSense.main(RepoSense.java:59)
```

### PR DESCRIPTION
**Pull request by fzdy1914**
Fixes #561 

Now, in DashboardServer, we use `isDesktopSupported` to test
whether the current Desktop is supported by the system.

However, in a headless system, this test passes but the `browse`
action is not supported, resulting exception to be thrown.

Let's add a test to test whether the `browse` action is supported 
by the current system.

### CODE REVIEW

**Comment by fzdy1914** [comment]
> According to docs (https://docs.oracle.com/javase/8/docs/api/java/awt/Desktop.html), `getDesktop()` throws `HeadlessException`. But if you tested and it works then should be fine.

Thanks for your suggestion, it works when I test on sunfire. 
@yong24s 
Can you help test on your headless system?

**Comment by yong24s** [comment]
Its actually Travis-CI. 😂 

No exception now.
https://travis-ci.org/reposense/RepoSense/jobs/500324644#L379

File: src/main/java/reposense/system/DashboardServer.java [hunk 1]
```diff
@@ -45,7 +45,7 @@ public static void startServer(int port, Path requestPath) {
      */
     private static void launchBrowser(String url) throws IOException {
         try {
-            if (Desktop.isDesktopSupported()) {
+            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
```
Comment (eugenepeh) [inline src/main/java/reposense/system/DashboardServer.java]: just to check, with the added condition, is the previous one `Desktop.isDesktopSupported()` still needed?

Comment (fzdy1914) [reply src/main/java/reposense/system/DashboardServer.java]: It is needed, otherwise, exception will be thrown during `Desktop.getDesktop()` if the desktop is not supported.
