### PR TITLE
[#2262] Update type adapter adding methods for gson builder

### LINKED ISSUE #2262: Old dashboards failing due to com.google.gson.JsonIOException
Some of my dashboards that I forgot to disable after the semester ended started failing recently.
Example: https://github.com/nus-cs2103-AY2324S2/ip-dashboard/actions/runs/12720039351/job/35461148355

Error:
```
Exception in thread "main" com.google.gson.JsonIOException: Failed making field 'java.time.ZoneRegion#id' accessible; either change its visibility or write a custom TypeAdapter for its declaring type
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:22)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
	at com.google.gson.Gson.getAdapter(Gson.java:501)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
	at com.google.gson.Gson.toJson(Gson.java:747)
	at com.google.gson.Gson.toJson(Gson.java:726)
	at com.google.gson.Gson.toJson(Gson.java:681)
	at com.google.gson.Gson.toJson(Gson.java:661)
	at reposense.util.FileUtil.writeJsonFile(FileUtil.java:117)
	at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:142)
	at reposense.RepoSense.main(RepoSense.java:79)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.time.ZoneRegion.id accessible: module java.base does not "opens java.time" to unnamed module @6a463b3d
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:19)
```

It is unlikely due to a change from our side but may be caused by a change from a dependency that we use or a change in CI environment. Still, we need to investigate.

### PR DESCRIPTION
**Pull request by CYX22222003**
Fixes #2262 

### Proposed commit message

```
Update GSON type adapter adding methods

The registration of custom adapters for ZoneID and LocalDateTime causes
The JsonIOException to pop up when trying to run the jar file in java
17.

Let's use the registerTypeHierarchyAdapter method to add the custom
adapters instead.
```

### Other information

Here are some reference resources I found online:
- https://stackoverflow.com/questions/74924830/why-is-gson-looking-for-java-time-zoneregion-when-serializing-java-time-zoneid
- https://www.javadoc.io/doc/com.google.code.gson/gson/2.6.2/com/google/gson/GsonBuilder.html#registerTypeHierarchyAdapter-java.lang.Class-java.lang.Object

### CODE REVIEW

**Review by lyuanww — COMMENTED** [review]
Thank you for the PR! It works with both Java 17 and Java 11 on my machine. I just have some small suggestions.

File: src/main/java/reposense/util/FileUtil.java [hunk 1]
```diff
@@ -29,26 +28,26 @@
...
+import reposense.util.adapters.DateSerializer;
+import reposense.util.adapters.ZoneSerializer;
 
 /**
  * Contains file processing related functionalities.
  */
 public class FileUtil {
     public static final String REPOS_ADDRESS = "repos";
-
+    public static final String GITHUB_API_DATE_FORMAT = "yyyy-MM-dd";
```
Comment (lyuanww) [inline src/main/java/reposense/util/FileUtil.java:45]: Would it be better to declare this in `DateSerializer.java` since it is only used there?

File: src/main/java/reposense/util/FileUtil.java [hunk 2]
```diff
@@ -29,26 +28,26 @@
...
     // zip file which contains all the specified file types
     public static final String ZIP_FILE = "archive.zip";
 
     private static final Logger logger = LogsManager.getLogger(FileUtil.class);
-    private static final String GITHUB_API_DATE_FORMAT = "yyyy-MM-dd";
+
```
Comment (lyuanww) [inline src/main/java/reposense/util/FileUtil.java:50]: Can you help to remove this blank line? Thank you!

**Review by lyuanww — APPROVED** [review]
LGTM!

File: src/main/java/reposense/util/FileUtil.java [hunk 3]
```diff
@@ -48,13 +47,10 @@ public class FileUtil {
     public static final String ZIP_FILE = "archive.zip";
 
     private static final Logger logger = LogsManager.getLogger(FileUtil.class);
-    private static final String GITHUB_API_DATE_FORMAT = "yyyy-MM-dd";
     private static final ByteBuffer buffer = ByteBuffer.allocate(1 << 11); // 2KB
-
```
Comment (sopa301) [inline src/main/java/reposense/util/FileUtil.java:53]: Nitpick: preserving these blank lines would help readability because they demarcate related groups

File: src/main/java/reposense/util/FileUtil.java [hunk 4]
```diff
@@ -48,13 +47,10 @@ public class FileUtil {
...
     private static final String BARE_REPO_SUFFIX = "_bare";
     private static final String PARTIAL_REPO_SUFFIX = "_partial";
     private static final String SHALLOW_PARTIAL_REPO_SUFFIX = "_shallow_partial";
-
```
Comment (sopa301) [inline src/main/java/reposense/util/FileUtil.java:57]: Ditto

**Review by sopa301 — APPROVED** [review]
LGTM, just some very minor nitpicks.
