### PR TITLE
[#904] Fix additional upward movement on expanding code

### LINKED ISSUE #904: Additional movement when expanding code
In some cases, when clicking the `+` button, the code seems to move up a bit before expanding.

expand-code

### PR DESCRIPTION
**Pull request by ang-zeyu**
Fixes #904 

```
Clicking the expand button may cause the code to move up a bit 
before expanding.

This occurs more frequently when the number of code lines to
load is large, or the client is slow. This is due to asynchronous
data loading by Vue, causing observable css updates to the
buttons before the code has been loaded into the DOM.

Let's execute the css change for the buttons only after the
the segment's code lines have been loaded.
```

### CODE REVIEW

File: frontend/src/static/js/v_segment.js [hunk 1]
```diff
@@ -9,7 +9,10 @@ window.vSegment = {
   methods: {
     loadCode() {
       this.loaded = true;
-      window.toggleNext(this.$el.childNodes[0]);
+      // For updating buttons only once code has loaded into DOM
```
Comment (fzdy1914) [inline frontend/src/static/js/v_segment.js]: Can be `Displaying code block only after the code has loaded into DOM`

Comment (ang-zeyu) [reply frontend/src/static/js/v_segment.js]: Indeed, I overlooked clarifying between dom / css updates. Thank you!

> Can be `Displaying code block only after the code has loaded into DOM`

Shouldn't this still be `For updating buttons only once code has loaded into DOM` though?
Since as you mentioned, the css update (buttons) follows the secondary dom update (v-for code)

Comment (fzdy1914) [reply frontend/src/static/js/v_segment.js]: It is just a suggestion. Actually, the CSS update not only updates the button but also controls the code block to be displayed, which is the major functionality of this CSS update. That's the reason I give the above recommendation.

**Comment by ang-zeyu** [comment]
Updated comment
