### PR TITLE
[#1190] Add message for invalid repository link on the summary view

### LINKED ISSUE #1190: RepoLocation: ftp protocol is accepted in repo url
To observe this, run RepoSense with the command 
`./gradlew run -Dargs="--repo ftp://github.com/reposense/RepoSense.git"`

RepoSense does not treat this as an invalid location, but tries to clone the repository (and fails):
image

Is this intended? 
Currently, we only use repo URLs for repos hosted on GitHub, and I do not think GitHub allows cloning over ftp

### PR DESCRIPTION
**Pull request by HCY123902**
Fixes #1190.

Commit message:
```
Add message on the report for invalid repository link

The current report generated does not show alert message
for link given by the user that cannot be recognized as a 
repository path.

Showing the message that the link provided is invalid can 
help the user to identify the reason why some repository 
is not shown in the report.

Let's add message for invalid link on the summary view
```

### CODE REVIEW

**Comment by gerhean** [comment]
image
Maybe add a full stop to be consistent? Or remove it from the second message?

Otherwise LGTM

**Comment by HCY123902** [comment]
> image
> Maybe add a full stop to be consistent? Or remove it from the second message?
> 
> Otherwise LGTM

Sure, no problem

**Review by dcshzj — APPROVED** [review]
LGTM!

File: src/main/java/reposense/model/RepoLocation.java [hunk 1]
```diff
@@ -68,6 +69,7 @@ private void verifyLocation(String location) throws InvalidLocationException {
         isValidGitUrl = matcher.matches();
 
         if (!isValidPathLocation && !isValidGitUrl) {
+            ErrorSummary.getInstance().addErrorMessage(location, "Invalid location.");
```
Comment (0blivious) [inline src/main/java/reposense/model/RepoLocation.java:72]: Would it be better to display the exact URL here? Sth like [URL] pointing to an invalid location

File: src/test/java/reposense/model/RepoConfigurationTest.java [hunk 2]
```diff
@@ -54,6 +54,7 @@
     private static final String TEST_REPO_DELTA = "https://github.com/reposense/testrepo-Delta.git";
     private static final String TEST_REPO_MINIMAL_STANDALONE_CONFIG =
             "https://github.com/reposense/testrepo-minimalstandaloneconfig.git";
+    private static final String INVALID_TEST_REPO = "ftp://github.com/reposense/testrepo-Delta.git";
```
Comment (0blivious) [inline src/test/java/reposense/model/RepoConfigurationTest.java:57]: should be TEST_REPO_INVALID_LOCATION

File: src/test/java/reposense/model/RepoConfigurationTest.java [hunk 3]
```diff
@@ -560,4 +561,17 @@ public void repoConfig_removeIgnoredAuthors_success() throws Exception {
 
         TestUtil.compareRepoConfig(expectedConfig, actualConfig);
     }
+
+    @Test
+    public void repoConfig_invalidLocation_success() throws Exception {
```
Comment (0blivious) [inline src/test/java/reposense/model/RepoConfigurationTest.java:566]: Assuming you are testing a case where cloning is failed? The naming should be sth like invalidLocation_fail or invalidLocation_throw...Exception

Comment (HCY123902) [reply src/test/java/reposense/model/RepoConfigurationTest.java:566]: Uh I am not sure about this because I am actually testing whether the invalid location will just be skipped and not added into the list of repositories that will be cloned and analyzed later. The expected behavior is that the exception will be caught by `getRepoConfigurations` and the method will skip the repository location accordingly

File: src/main/java/reposense/model/RepoLocation.java (hunk 1 above)
Comment (HCY123902) [reply src/main/java/reposense/model/RepoLocation.java:72]: Sure, no problem

File: src/test/java/reposense/model/RepoConfigurationTest.java (hunk 2 above)
Comment (HCY123902) [reply src/test/java/reposense/model/RepoConfigurationTest.java]: Thanks for the suggestion. I have changed it accordingly

**Review by 0blivious — APPROVED** [review]

**Review by Tejas2805 — APPROVED** [review]
LGTM!
