### PR TITLE
[#1084] Authorship: append file type label

### LINKED ISSUE #1084: Authorship view: Sort by FileType
When files are sorted by `fileType`, the following occurs where `java` test files are not in order...

Screen Shot 2020-02-15 at 2 37 37 PM

[Link to reproduce](https://deploy-preview-1074--reposense.netlify.com/#search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=AdityaA1998&tabRepo=reposense%2FRepoSense%5Bmaster%5D)

_Originally posted by @jamessspanggg in [1074](https://github.com/reposense/RepoSense/pull/1074#issuecomment-586560683_)

### PR DESCRIPTION
**Pull request by 0blivious**
Fixes #1084
```
The user has no means to see the file belong to which file group.

This can be improved by appending a label at the end of the file
title to allow user get an easy view of which file type the file
belongs to.

Let's append a coloured label at the end of the file title to indicate
which file type the tile belongs to.
```

### CODE REVIEW

File: frontend/src/static/js/v_authorship.js [hunk 1]
```diff
@@ -201,6 +207,18 @@ window.vAuthorship = {
       this.activeFilesCount = this.selectedFiles.length;
     },
 
+    getFontColor(color) {
```
Comment (jamessspanggg) [inline frontend/src/static/js/v_authorship.js]: This actually overlaps with #1025. Perhaps wait for that PR to be merged first?

Comment (0blivious) [reply frontend/src/static/js/v_authorship.js]: not very sure if it is worthy to add a global function

Comment (jamessspanggg) [reply frontend/src/static/js/v_authorship.js]: Perhaps in a util class?

Comment (0blivious) [reply frontend/src/static/js/v_authorship.js]: can but should that be a seperate pr? to move all global func into util.js

**Comment by jamessspanggg** [comment]
> The user has no means to see the commit belong to which file group.

^ from ur pr message, do you mean file instead of commit?

File: frontend/src/tabs/authorship.pug [hunk 2]
```diff
@@ -57,17 +64,22 @@
...
+              i.button.fas.fa-history
+            a(
+              v-bind:href="getFileLink(file, 'blame')", target="_blank",
+              title="click to view the blame view of file"
+            )
+              i.button.fas.fa-user-edit
+          span.fileTypeLabel(
+            v-bind:style="{\
+              'background-color' : fileTypeColors[file.fileType],\
+              'color' : $getFontColor(fileTypeColors[file.fileType])}"
```
Comment (jamessspanggg) [inline frontend/src/tabs/authorship.pug]: perhaps can place the `}` in a new line?

File: frontend/src/static/js/main.js [hunk 3]
```diff
@@ -1,3 +1,21 @@
+const Util = {
```
Comment (jamessspanggg) [inline frontend/src/static/js/main.js]: Hmm, I'm not so sure about this way of creating a util method is the best way. @ang-zeyu may I get your opinion on this?

File: frontend/src/static/css/v_authorship.scss [hunk 4]
```diff
@@ -31,6 +31,20 @@
         display: flex;
         margin-left: 3rem;
         margin-top: 1.0rem;
+
+        .checkboxes {
+          label {
+            align-items: center;
+            border-radius: 5px;
+            display: inline-flex;
```
Comment (ang-zeyu) [inline frontend/src/static/css/v_authorship.scss]: Seems like there's already a label selector below that applies the `display` and `align-items`, could remove these perhaps

File: frontend/src/tabs/authorship.pug [hunk 5]
```diff
@@ -37,18 +37,26 @@
       .fileType
         input.radio-button--checkbox(type="radio", value="checkboxes", v-model="filterType")
         .checkboxes.mui-form--inline(v-if="files.length > 0")
-          label
+          label(
```
Comment (ang-zeyu) [inline frontend/src/tabs/authorship.pug]: minor style nit: maybe make it oneline here? since there's only one attribute

There's an extra space before the `:` in `color : #ffffff` too

File: frontend/src/static/js/v_summary.js [hunk 6]
```diff
@@ -14,6 +14,18 @@ window.comparator = (fn) => function compare(a, b) {
   return 1;
 };
 
+window.getFontColor = function getFontColor(color) {
```
Comment (ang-zeyu) [inline frontend/src/static/js/v_summary.js]: would `main.js` or `api.js` be better? since its used in multiple components

File: frontend/src/static/js/v_authorship.js [hunk 7]
```diff
@@ -35,6 +35,8 @@ window.vAuthorship = {
       filterType: 'checkboxes',
       selectedFileTypes: [],
       fileTypes: [],
+      fileTypeColors: {},
+      checkBoxFileTypeFontColors: {},
```
Comment (ang-zeyu) [inline frontend/src/static/js/v_authorship.js]: unused variable

File: frontend/src/tabs/authorship.pug [hunk 8]
```diff
@@ -37,18 +37,26 @@
...
               span.select.medium-font All:&nbsp;
               span.loc.medium-font {{ totalLineCount }}&nbsp;
               span.bloc.medium-font ({{ totalBlankLineCount }})
           template(v-for="fileType in Object.keys(getFileTypeExistingLinesObj)")
-            label(v-bind:key="fileType")
+            label(
+              v-bind:key="fileType",
+              v-bind:style="{\
+                'background-color' : fileTypeColors[fileType],\
+                'color' : this.getFontColor(fileTypeColors[fileType])\
```
Comment (ang-zeyu) [inline frontend/src/tabs/authorship.pug]: extra spaces before `:`

File: frontend/src/tabs/authorship.pug [hunk 9]
```diff
@@ -57,17 +65,23 @@
...
+              i.button.fas.fa-history
+            a(
+              v-bind:href="getFileLink(file, 'blame')", target="_blank",
+              title="click to view the blame view of file"
+            )
+              i.button.fas.fa-user-edit
+          span.fileTypeLabel(
+            v-bind:style="{\
+              'background-color' : fileTypeColors[file.fileType],\
+              'color' : this.getFontColor(fileTypeColors[file.fileType])\
```
Comment (ang-zeyu) [inline frontend/src/tabs/authorship.pug]: extra spaces

File: frontend/src/summary.pug [hunk 10]
```diff
@@ -91,15 +91,17 @@
   .fileTypes(v-if="filterBreakdown")
     .checkboxes.mui-form--inline(v-if="Object.keys(fileTypeColors).length > 0")
       label(
-        v-bind:style="{ 'background-color' : '#000000', 'color' : '#ffffff' }"
+        style='background-color: #000000; color : #ffffff'
```
Comment (ang-zeyu) [inline frontend/src/summary.pug]: > minor style nit: maybe make it oneline here? since there's only one attribute
> There's an extra space before the : in color : #ffffff too

two more below for the `v-bind` as well

File: frontend/src/static/js/v_summary.js (hunk 6 above)
Comment (0blivious) [reply frontend/src/static/js/v_summary.js]: I feel api should contain what is for loading and the main is very crowded alr. I have another PR moving every window function into util.js. Will just put the function in v_summary here, depending on which one merge first.

File: frontend/src/tabs/authorship.pug [hunk 11]
```diff
@@ -57,17 +63,23 @@
...
+            a(
+              v-bind:href="getFileLink(file, 'blame')", target="_blank",
+              title="click to view the blame view of file"
+            )
+              i.button.fas.fa-user-edit
+          span.fileTypeLabel(
+            v-bind:style="{\
+              'background-color': fileTypeColors[file.fileType],\
+              'color': this.getFontColor(fileTypeColors[file.fileType])\
+              }"
```
Comment (jamessspanggg) [inline frontend/src/tabs/authorship.pug]: the indentation of closing braces should be in the same line as `v-bind`?

File: frontend/src/tabs/authorship.pug [hunk 12]
```diff
@@ -37,18 +37,24 @@
...
               span.loc.medium-font {{ totalLineCount }}&nbsp;
               span.bloc.medium-font ({{ totalBlankLineCount }})
           template(v-for="fileType in Object.keys(getFileTypeExistingLinesObj)")
-            label(v-bind:key="fileType")
+            label(
+              v-bind:key="fileType",
+              v-bind:style="{\
+                'background-color': fileTypeColors[fileType],\
+                'color': this.getFontColor(fileTypeColors[fileType])\
+                }"
```
Comment (jamessspanggg) [inline frontend/src/tabs/authorship.pug]: same for this

File: frontend/src/summary.pug [hunk 13]
```diff
@@ -90,16 +90,16 @@
...
         span All:&nbsp;
       template(v-for="fileType in Object.keys(fileTypeColors)" )
         label(
           v-bind:key="fileType",
-          v-bind:style="{ 'background-color' : fileTypeColors[fileType], \
-                    'color' : getFontColor(fileTypeColors[fileType])}"
+          v-bind:style="{\
+            'background-color': fileTypeColors[fileType], \
+            'color': this.getFontColor(fileTypeColors[fileType])\
+            }"
```
Comment (jamessspanggg) [inline frontend/src/summary.pug]: here too

File: frontend/src/tabs/authorship.pug (hunk 11 above)
Comment (0blivious) [reply frontend/src/tabs/authorship.pug]: If you consider the closing braces just as a part of the string, then it should be 2 space after v-bind? Following the style in ramp.pug line 17

Comment (jamessspanggg) [reply frontend/src/tabs/authorship.pug]: hmmmm right, i was referring to line 42 of ramp.pug. Nvm then, ignore the comments

File: frontend/src/static/css/v_authorship.scss [hunk 14]
```diff
@@ -136,6 +132,18 @@
         margin-left: .5rem;
         text-decoration: none;
       }
+
+      .icons {
+        margin-right: 8px;
+        vertical-align: middle;
+      }
+
+      .fileTypeLabel{
```
Comment (eugenepeh) [inline frontend/src/static/css/v_authorship.scss:141]: space before curly bracket, can you also help me to put up an issue to add this to style check?

File: frontend/src/static/css/v_authorship.scss [hunk 15]
```diff
@@ -20,13 +20,25 @@
...
     .contribution {
-      color: mui-color('red');
-
       .fileType {
         align-items: center;
         display: flex;
         margin-left: 3rem;
         margin-top: 1.0rem;
+
+        .checkboxes {
```
Comment (eugenepeh) [inline frontend/src/static/css/v_authorship.scss:29]: would it be possible for it to utilize the style from summary given that they have the same properties?

File: frontend/src/summary.pug [hunk 16]
```diff
@@ -90,16 +90,14 @@
...
+      label(style='background-color: #000000; color: #ffffff')
         input.mui-checkbox--fileType(type="checkbox", v-model="checkAllFileTypes")
         span All:&nbsp;
       template(v-for="fileType in Object.keys(fileTypeColors)" )
         label(
           v-bind:key="fileType",
-          v-bind:style="{ 'background-color' : fileTypeColors[fileType], \
-            'color' : getFontColor(fileTypeColors[fileType])}"
+          v-bind:style="{ 'background-color': fileTypeColors[fileType], \
+            'color': this.getFontColor(fileTypeColors[fileType])}"
```
Comment (eugenepeh) [inline frontend/src/summary.pug:100]: please do also highlight this to be added into style check.
Is there a need to modify it in this PR?

Comment (0blivious) [reply frontend/src/summary.pug:100]: This PR adds several similar code block for file type lable in authorship.pug. I feel it would be better to standardize the spacing in this PR

File: frontend/src/static/css/v_authorship.scss (hunk 14 above)
Comment (0blivious) [reply frontend/src/static/css/v_authorship.scss:141]: done

File: frontend/src/static/css/v_authorship.scss (hunk 15 above)
Comment (0blivious) [reply frontend/src/static/css/v_authorship.scss]: can. As this is a common style I shift them to panel.scss

File: frontend/src/summary.pug (hunk 16 above)
Comment (eugenepeh) [reply frontend/src/summary.pug:100]: actually my question is, is there any difference between `getFontColor` and `this.getFontColor`? 
If there isn't then there is no need to make modifications to this file for this PR.

Comment (0blivious) [reply frontend/src/summary.pug:100]: I made getFontColor to be window function. Without the `this` there will be `method "getFontColor" is not defined` error and the checkboxes will not be rendered

File: frontend/src/static/css/v_authorship.scss [hunk 17]
```diff
@@ -136,6 +111,18 @@
...
+
+      .icons {
+        margin-right: 8px;
+        vertical-align: middle;
+      }
+
+      .fileTypeLabel {
+        border-radius: 5px;
+        display: inline-block;
+        font-size: 15px;
```
Comment (jamessspanggg) [inline frontend/src/static/css/v_authorship.scss:123]: is it possible to standardise the size across all file type labels? i.e. using our custom `medium-font` css

File: frontend/src/tabs/authorship.pug [hunk 18]
```diff
@@ -58,17 +64,23 @@
...
+              v-bind:href="getFileLink(file, 'blame')", target="_blank",
+              title="click to view the blame view of file"
+            )
+              i.button.fas.fa-user-edit
+          span.fileTypeLabel(
+            v-bind:style="{\
+              'background-color': info.fileTypeColors[file.fileType],\
+              'color': this.getFontColor(info.fileTypeColors[file.fileType])\
+              }"
+          ) {{file.fileType}}: {{ file.lineCount }} lines
```
Comment (jamessspanggg) [inline frontend/src/tabs/authorship.pug:83]: spacing in between `{{ file.fileType }}`

**Comment by jamessspanggg** [comment]
When trying to reload the site with authorship tab opened, it shows the following console error while the page keeps loading without stopping:

Screen Shot 2020-04-16 at 3 46 54 PM

To replicate, go to your preview, view author `eugene peh`'s code. Reload the page and observe the console error and the loading of authorship panel.

File: frontend/src/static/css/v_authorship.scss [hunk 19]
```diff
@@ -120,7 +120,7 @@
       .fileTypeLabel {
         border-radius: 5px;
         display: inline-block;
-        font-size: 15px;
+        font-size: medium;
```
Comment (jamessspanggg) [inline frontend/src/static/css/v_authorship.scss:123]: not the default `medium` css but our custom `medium-font` class

**Comment by jamessspanggg** [comment]
Also, should we also display the number of blank lines contributed for each file? Since the main file type checkboxes contain this info. Should be straight forward to obtain the number of blank lines contributed for each file, can modify in the `processFile` method.

@damithc your opinion on this?

Screen Shot 2020-04-16 at 10 29 34 PM

**Comment by damithc** [comment]
> Also, should we also display the number of blank lines contributed for each file? Since the main file type checkboxes contain this info. Should be straight forward to obtain the number of blank lines contributed for each file, can modify in the `processFile` method.
> 
> @damithc your opinion on this?

I don't mind. BTW, we can omit the word `lines` in the interest of saving space?
Also, I don't think we should use colon in `frontend: 45` as 45 is not the value of `frontend`. Something like this? `frontend 45 (16)`

File: frontend/src/static/css/v_authorship.scss [hunk 20]
```diff
@@ -136,6 +101,18 @@
...
+
+      .icons {
+        margin-right: 8px;
+        vertical-align: middle;
+      }
+
+      .fileTypeLabel {
+        border-radius: 5px;
+        display: inline-block;
+        font-weight: bold;
```
Comment (0blivious) [inline frontend/src/static/css/v_authorship.scss:113]: The font-weight bold is reserved for first-timer issue

Comment (jamessspanggg) [reply frontend/src/static/css/v_authorship.scss]: I think what prof meant was to leave the removal of `font-weight: bold;` as a first timer issue 😂

**Comment by Tejas2805** [comment]
Found a bug. Please fix it and ask for review again. 

Screen Shot 2020-04-18 at 3 24 15 PM

**Comment by jamessspanggg** [comment]
> Found a bug. Please fix it and ask for review again. 
> 

It’s actually not a bug. Introduced in #1065

**Comment by Tejas2805** [comment]
> > Found a bug. Please fix it and ask for review again.
> 
> It’s actually not a bug. Introduced in #1065

Ah I see. I had missed that PR. But won't having both affect how it looks? I felt it looked a bit weird :(

**Comment by 0blivious** [comment]
> Perhaps can remove the `getFontColor` here

removed but have to move getHexToRGBColor outside of component for window method to access it

File: frontend/src/static/js/v_summary.js [hunk 21]
```diff
@@ -39,6 +24,26 @@ function dateRounding(datestr, roundDown) {
   return window.getDateStr(datems);
 }
 
+window.deactivateAllOverlays = function deactivateAllOverlays() {
```
Comment (jamessspanggg) [inline frontend/src/static/js/v_summary.js:27]: The moving of these two methods are not needed for this PR right?

Comment (0blivious) [reply frontend/src/static/js/v_summary.js:27]: just want to group all window method together and function together.
I need to have getHex before window.getFontColor, but then I will have sth like
```
function getHex
window.func
window.func
function getDate
```

Comment (jamessspanggg) [reply frontend/src/static/js/v_summary.js:27]: I think this can be in another PR as these two methods are unrelated to this PR. We usually do not modify code that is not related to the PR.

**Comment by eugenepeh** [comment]
since `label` is used in the variable name, keep it consistent in the commit message as well
