### PR TITLE
[#918] Bugfix: add catch-all clause on analysis of each repo

### LINKED ISSUE #918: Better exception handling: Uncaught exception while analysing one repository causes whole report generation to fail
Bug in #917 leads to an uncaught exception. This causes the whole report generation to fail although only one repository has a problem. Users should still be able to generate the report even though some repositories encountered failures during analysis.

### PR DESCRIPTION
**Pull request by myteo**
Fixes #918.

```
In #917, an exception during the analysis one of the CS2103 student
repositories caused the report generation to fail for other
repositories as well.

This occurred because the bug led to an exception that was not being
caught.

Even after #917 is fixed, there might still be other undiscovered
bugs which can lead to uncaught exceptions. Lets add a catch-all
clause during the analysis of a single repository so that uncaught
exceptions will not affect other repositories.
```

### CODE REVIEW

**Comment by yong24s** [comment]
It is possible to surface the error to the report, so proactive users can report the bugs to us?

i.e.
```
Opps!
We are actively looking for ways to improve RepoSense. 
Please consider using this LINK to report the issue to us.
```
[Example link](https://github.com/reposense/RepoSense/issues/new?title=Unhandled%20errors...&body=Logs.....)

@damithc, what do you think?

**Comment by damithc** [comment]
> @damithc, what do you think?

We can do that 👍 .  Are things caught in this catch block likely to be due to RepoSense bugs?

**Comment by myteo** [comment]
> Are things caught in this catch block likely to be due to RepoSense bugs?

I think they will likely be due to edge cases that are not being handled (eg. special file names). We have other catch blocks for specific exceptions that we anticipate before the catch-all block.

**Comment by myteo** [comment]
Screenshot 2019-10-16 at 2 11 19 PM

Something like this?

**Comment by damithc** [comment]
How about this?
> Oops, an unexpected error occurred. If you think this is due to a problem in RepoSense, please report in [our issue tracker]() or email us at seer@comp.nus.edu.sg

**Comment by eugenepeh** [comment]
>Done.

For the template, I think it will be nice to assist the user in filling in the important details.
E.g. 
Title can be `Unexpected error with RepoSense (VERSION_NUMBER)`
Content can include the url of the repository, stack trace, logs or etc.

**Comment by myteo** [comment]
Thanks for the suggestion, the link will now be something like [this](https://github.com/reposense/RepoSense/issues/new?title=Unexpected%20error%20with%20RepoSense%20version%20a98ec7e5c0&body=Unexpected%20error%20stack%20trace%20for%20https://github.com/AY1920S1-CS2103T-T12-1/main.git:%0A>java.lang.IndexOutOfBoundsException:%20Index:%2031,%20Size:%2031%0A%09at%20java.util.ArrayList.rangeCheck(ArrayList.java:653)%0A%09at%20java.util.ArrayList.get(ArrayList.java:429)%0A%09at%20reposense.authorship.FileInfoExtractor.setLinesToTrack(FileInfoExtractor.java:165)%0A%09at%20reposense.authorship.FileInfoExtractor.getEditedFileInfos(FileInfoExtractor.java:117)%0A%09at%20reposense.authorship.FileInfoExtractor.extractFileInfos(FileInfoExtractor.java:70)%0A%09at%20reposense.authorship.AuthorshipReporter.generateAuthorshipSummary(AuthorshipReporter.java:21)%0A%09at%20reposense.report.ReportGenerator.analyzeRepo(ReportGenerator.java:230)%0A%09at%20reposense.report.ReportGenerator.analyzeRepos(ReportGenerator.java:192)%0A%09at%20reposense.report.ReportGenerator.cloneAndAnalyzeRepos(ReportGenerator.java:162)%0A%09at%20reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:99)%0A%09at%20reposense.RepoSense.main(RepoSense.java:63)%0A).

**Comment by eugenepeh** [comment]
>Thanks for the suggestion, the link will now be something like this.

Looks good 👍 
Is it possible to do the same for email too?

**Comment by myteo** [comment]
> > Thanks for the suggestion, the link will now be something like this.
> 
> Looks good 👍
> Is it possible to do the same for email too?

Sure, done for email.

File: frontend/src/static/js/v_summary.js [hunk 1]
```diff
@@ -278,6 +278,22 @@ window.vSummary = {
...
     },
 
+    getReportIssueLink(stackTrace) {
+      return 'https://github.com/reposense/RepoSense/issues/new?title=' +
+          encodeURI('Unexpected error with RepoSense version ') + window.app.repoSenseVersion + '&body=' +
+          encodeURI(stackTrace);
+    },
+
+    getReportIssueEmailAddress() {
+      return 'seer@comp.nus.edu.sg';
```
Comment (eugenepeh) [inline frontend/src/static/js/v_summary.js]: this can be inlined into the `getReportIssueEmailLink` since its only used once.

File: frontend/src/static/js/v_summary.js [hunk 2]
```diff
@@ -278,6 +278,22 @@ window.vSummary = {
       return repo.location;
     },
 
+    getReportIssueLink(stackTrace) {
```
Comment (eugenepeh) [inline frontend/src/static/js/v_summary.js]: `getReportIssueLink` -> `getReportIssueGitHubLink`

File: frontend/src/static/js/v_summary.js [hunk 3]
```diff
@@ -278,6 +278,22 @@ window.vSummary = {
...
+      return 'https://github.com/reposense/RepoSense/issues/new?title=' +
+          encodeURI('Unexpected error with RepoSense version ') + window.app.repoSenseVersion + '&body=' +
+          encodeURI(stackTrace);
```
Comment (eugenepeh) [inline frontend/src/static/js/v_summary.js]: The `encodeURI('Unexpected error with RepoSense version ') + window.app.repoSenseVersion` and `encodeURI(stackTrace)` can be split into `getReportIssueTitle` and `getReportIssueMessage` respectively for usability (also single point of modification).

File: frontend/src/static/js/v_summary.js (hunk 1 above)
Comment (myteo) [reply frontend/src/static/js/v_summary.js]: `getReportIssueEmailAddress` is also called in `index.pug` to get the displayed text for the link

Comment (eugenepeh) [reply frontend/src/static/js/v_summary.js]: I see 👍

File: src/main/java/reposense/report/ReportGenerator.java [hunk 4]
```diff
@@ -204,6 +207,12 @@ private static void analyzeRepos(String outputPath, List<RepoConfiguration> conf
                 logger.log(Level.WARNING, String.format(MESSAGE_NO_AUTHORS_WITH_COMMITS_FOUND,
                         configToAnalyze.getLocation(), configToAnalyze.getBranch()));
                 generateEmptyRepoReport(repoReportDirectory.toString(), Author.NAME_NO_AUTHOR_WITH_COMMITS_FOUND);
+            } catch (Exception e) {
+                StringWriter sw = new StringWriter();
+                e.printStackTrace(new PrintWriter(sw));
+                logger.log(Level.SEVERE, sw.toString());
+                handleAnalysisFailed(configs, configToAnalyze, String.format(
+                        LOG_UNEXPECTED_ERROR, configToAnalyze.getLocation(), sw.toString()));
```
Comment (eugenepeh) [inline src/main/java/reposense/report/ReportGenerator.java]: Higher level line break is preferred if it is allowed
```
                handleAnalysisFailed(configs, configToAnalyze, 
                        String.format(LOG_UNEXPECTED_ERROR, configToAnalyze.getLocation(), sw.toString()));
```

**Comment by myteo** [comment]
@damithc could you take a look at this PR? thanks!
