### PR TITLE
InvalidPathException thrown during run time due to Illegal char <:> in file name #370

### LINKED ISSUE #370: InvalidPathException thrown during run time due to Illegal char <:> in file name
image

### PR DESCRIPTION
**Pull request by yamidark**
Fixes #370 
```
Windows disallows certain characters for the file names, such as `/\:*?"<>|`,
while other OSes like Linux allows almost any characters for their file names.
This may result in some files with such `banned` characters in the repository
to not be copied/cloned into a local copy for Windows OS.

As we use the `git diff` command to find file differences for analyzing
repositories with a date range, such files with `banned` characters may appear
in the `git diff` result, which result in an InvalidPathException being thrown
when we try to create a Path to this file name, which is invalid in Windows.
This causes the program to crash as the exception is not handled anywhere.

Let's update FileInfoExtractor to handle files with invalid file names by
skipping those files.
```

### CODE REVIEW

File: src/main/java/reposense/authorship/FileInfoExtractor.java [hunk 1]
```diff
@@ -104,7 +106,15 @@
...
+                try {
+                    currentFileInfo = generateFileInfo(config.getRepoRoot(), filePath);
+                } catch (InvalidPathException ipe) {
+                    logger.warning(String.format(INVALID_FILE_PATH_MESSAGE_FORMAT, filePath));
+                    continue;
+                }
+
                 setLinesToTrack(currentFileInfo, fileDiffResult);
                 fileInfos.add(currentFileInfo);
             }
```
Comment (yong24s) [inline src/main/java/reposense/authorship/FileInfoExtractor.java]: Not sure if the `continue` in the `catch` block is necessary.

Try simplify it like this?

```
if (isFormatInsideWhiteList(filePath, config.getFormats())) {    
    try {
        // generateFileInfo may throw InvalidPathException 
        FileInfo currentFileInfo = generateFileInfo(config.getRepoRoot(), filePath);
        setLinesToTrack(currentFileInfo, fileDiffResult);
        fileInfos.add(currentFileInfo);
    } catch (InvalidPathException ipe) {
        logger.warning(String.format(INVALID_FILE_PATH_MESSAGE_FORMAT, filePath));
    }
}
```
