### PR TITLE
Extracting info from git diff is not working as expected #215

### LINKED ISSUE #215: Extracting info from git diff is not working as expected
Following #205, running with since date result in following error.

```
java -jar RepoSense.jar -config interns.csv -since 15/05/2018 -formats java adoc js md css jsp tag xml fxml gradle
03:10:08 - Cloning reposense/reposense...
03:10:14 - Cloning completed!
03:10:14 - Extracting commits info for reposense_reposense_master...
03:10:15 - Extracting relevant file infos reposense_reposense_master...
Exception in thread "main" java.lang.AssertionError: Should not have error matching file path pattern inside file diff result!
        at reposense.authorship.FileInfoExtractor.getFilePathFromDiffPattern(FileInfoExtractor.java:205)
        at reposense.authorship.FileInfoExtractor.getEditedFileInfos(FileInfoExtractor.java:92)
        at reposense.authorship.FileInfoExtractor.extractFileInfos(FileInfoExtractor.java:60)
        at reposense.authorship.AuthorshipReporter.generateAuthorshipSummary(AuthorshipReporter.java:21)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:53)
        at reposense.RepoSense.main(RepoSense.java:27)
```

### PR DESCRIPTION
**Pull request by yamidark**
Fixes #215:
```
FileInfoExtractor#getFilePathFromDiffPattern(String) checks
for the group pattern '+++ b/path/to/file'
within the git diff result in order to get the file path.

However, when a new and also empty file is added in between the
commit range to analysis, the file will appear in the git diff result,
but since there are no lines to display, the above group does not
get printed, thus 
FileInfoExtractor#getFilePathFromDiffPattern(String) is unable
to match the pattern, causing the program to crash.

Let's add a check to skip these new and empty files in 
the git diff result, since an empty file has no lines to 
attribute any contribution.
```

### CODE REVIEW

**Comment by yamidark** [comment]
@eugenepeh For your review.

File: src/main/java/reposense/authorship/FileInfoExtractor.java [hunk 1]
```diff
@@ -84,8 +89,9 @@
         String[] fileDiffResultList = fullDiffResult.split(DIFF_FILE_CHUNK_SEPARATOR);
 
         for (String fileDiffResult : fileDiffResultList) {
-            // file deleted or is a binary file, skip it
-            if (fileDiffResult.startsWith(FILE_DELETED_METADATA) || fileDiffResult.contains(BINARY_FILE_SYMBOL)) {
+            // file deleted, is binary file or is new and empty file, skip it
+            if (fileDiffResult.startsWith(FILE_DELETED_METADATA) || fileDiffResult.contains(BINARY_FILE_SYMBOL)
+                    || NEW_EMPTY_FILE_PREDICATE.test(fileDiffResult)) {
```
Comment (eugenepeh) [inline src/main/java/reposense/authorship/FileInfoExtractor.java]: actually, why don't do it similarly as `FILE_DELETED_METADATA`?

Comment (yamidark) [reply src/main/java/reposense/authorship/FileInfoExtractor.java]: For files that are deleted,the `git diff` result will still print out all the lines in the file (as deleted)
A new file also does the same, printing out all the lines in the file (as added).
However, what we are checking here is a special case where if we add a new file, but that file is empty, thus not having the header group we are trying to find, or any lines to print as well.

File: src/main/java/reposense/authorship/FileInfoExtractor.java [hunk 2]
```diff
@@ -36,13 +37,17 @@
...
+    private static final String MATCH_GROUP_FAIL_MESSAGE_FORMAT = "Failed to match the %s group for:\n%s";
 
     private static final int LINE_CHANGED_HEADER_INDEX = 0;
 
     private static final Pattern STARTING_LINE_NUMBER_PATTERN = Pattern.compile(
             "-(\\d)+(,)?(\\d)* \\+(?<startingLineNumber>\\d+)(,)?(\\d)* @@");
     private static final Pattern FILE_CHANGED_PATTERN = Pattern.compile("\n(\\+){3} b/(?<filePath>.*)\n");
 
+    private static final Predicate<String> NEW_EMPTY_FILE_PREDICATE = Pattern.compile("^new file mode 100644\n"
+            + "index [a-zA-Z0-9]{7}\\.{2}[a-zA-Z0-9]{7}$").asPredicate();
```
Comment (eugenepeh) [inline src/main/java/reposense/authorship/FileInfoExtractor.java]: `\\.` seems like an additional `\` here.
But anyway, let's make use of the `+++` and `---` functionality and simplify this
-> `^new file mode [a-zA-Z0-9\n\. ]*$`

**Comment by eugenepeh** [comment]
for the `deleted file mode` please simplify it to exclude the digit as well. I think the number represents file permission, so if someone adds the file with other permission levels, it may bypass this test.

File: src/main/java/reposense/authorship/FileInfoExtractor.java (hunk 2 above)
Comment (yamidark) [reply src/main/java/reposense/authorship/FileInfoExtractor.java]: >\\. seems like an additional \ here.

There is a need for 2 `\`, since the 1st `\` is meant to tell that the 2nd `\` is the actual backslash rather than an escape character.
Anyway, within the square brackets, there is no need for `\` :sweat_smile:.

Comment (eugenepeh) [reply src/main/java/reposense/authorship/FileInfoExtractor.java]: I see, I am used to using online regex test so I kinda forgot the syntax for java.

File: src/main/java/reposense/authorship/FileInfoExtractor.java [hunk 3]
```diff
@@ -90,7 +91,7 @@
 
         for (String fileDiffResult : fileDiffResultList) {
             // file deleted, is binary file or is new and empty file, skip it
-            if (fileDiffResult.startsWith(FILE_DELETED_METADATA) || fileDiffResult.contains(BINARY_FILE_SYMBOL)
+            if (FILE_DELETED_PREDICATE.test(fileDiffResult) || fileDiffResult.contains(BINARY_FILE_SYMBOL)
```
Comment (eugenepeh) [inline src/main/java/reposense/authorship/FileInfoExtractor.java]: Wouldn't this fail if you replace `startsWith` with predicate test?

File: src/main/java/reposense/authorship/FileInfoExtractor.java [hunk 4]
```diff
@@ -84,8 +90,9 @@
         String[] fileDiffResultList = fullDiffResult.split(DIFF_FILE_CHUNK_SEPARATOR);
 
         for (String fileDiffResult : fileDiffResultList) {
-            // file deleted or is a binary file, skip it
-            if (fileDiffResult.startsWith(FILE_DELETED_METADATA) || fileDiffResult.contains(BINARY_FILE_SYMBOL)) {
+            // file deleted, is binary file or is new and empty file, skip it
+            if (FILE_DELETED_PREDICATE.test(fileDiffResult) || fileDiffResult.contains(BINARY_FILE_SYMBOL)
```
Comment (eugenepeh) [inline src/main/java/reposense/authorship/FileInfoExtractor.java]: Wouldn't this fail if you replace `startsWith` with predicate test?

Comment (yamidark) [reply src/main/java/reposense/authorship/FileInfoExtractor.java]: >Wouldn't this fail if you replace startsWith with predicate test?

The predicate has `^` at the start to indicate that the `String` must start with this pattern, thus its the same as `startsWith`, just that `startWith` must be an exact `String`, while we need to check for  a pattern.
