### PR TITLE
Shift from File to Path class #107

### LINKED ISSUE #107: Shift from File to Path class
java.nio.file.Path is able to do everything java.io.File can and generally in a better way. This is supported by the document posted on the website https://docs.oracle.com/javase/tutorial/essential/io/legacy.html.

Let's move towards to using Path as a replacement to File whenever we can for better exception handling and OS invariant coding.

### PR DESCRIPTION
**Pull request by yamidark**
Fixes #107 
```
java.nio.file.Path is able to do everything java.io.File can and generally in a better way. 
This is supported by the document posted on the website
https://docs.oracle.com/javase/tutorial/essential/io/legacy.html.

Let's move towards to using Path as a replacement to File whenever we can for better
exception handling and OS invariant coding.
```

### CODE REVIEW

File: src/main/java/reposense/system/CommandRunner.java [hunk 1]
```diff
@@ -21,47 +23,49 @@ public static String gitLog(String root, Date fromDate, Date toDate) {
...
 
     public static String cloneRepo(String org, String repoName) {
-        File rootFile = new File(Constants.REPOS_ADDRESS + "/" + org);
-        if (!rootFile.exists()) {
-            rootFile.mkdirs();
+        Path rootPath = Paths.get(Constants.REPOS_ADDRESS, org);
+        try {
+            Files.createDirectories(rootPath);
+        } catch (IOException ioe) {
+            ioe.printStackTrace();
```
Comment (eugenepeh) [inline src/main/java/reposense/system/CommandRunner.java]: perhaps let the calling method handle the exception instead?

File: src/main/java/reposense/util/FileUtil.java [hunk 2]
```diff
@@ -40,131 +41,52 @@ public static String getRepoDirectory(String org, String repoName) {
...
+                        .forEach(FileUtil::deleteFile);
             }
-
-        } else {
-            //if file, then copy it
-            //Use bytes stream to support all file types
-            copyFile(src, dest);
-            //System.out.println("File copied from " + src + " to " + dest);
+        } catch (IOException ioe) {
+            ioe.printStackTrace();
```
Comment (eugenepeh) [inline src/main/java/reposense/util/FileUtil.java]: same as previous

File: src/test/java/reposense/analyzer/FileAnalyzerTest.java [hunk 3]
```diff
@@ -23,7 +22,7 @@ public void allFileTest() {
         Assert.assertEquals(files.size(), 4);
         Assert.assertTrue(isFileExistence("annotationTest.java", files));
         Assert.assertTrue(isFileExistence("blameTest.java", files));
-        Assert.assertTrue(isFileExistence("newPos" + File.separator + "movedFile.java", files));
```
Comment (eugenepeh) [inline src/test/java/reposense/analyzer/FileAnalyzerTest.java]: I think this is fine to retain

**Comment by yamidark** [comment]
@eugenepeh Made the changes, for your review again.

File: src/main/java/reposense/git/GitCloner.java [hunk 4]
```diff
@@ -19,6 +21,9 @@ public static void downloadRepo(String organization, String repoName, String bra
             throw new GitClonerException(e);
             //Due to an unsolved bug on Windows Git, for some repository, Git Clone will return an error even
             // though the repo is cloned properly.
+        } catch (IOException ioe) {
+            System.out.println("Error creating/deleting directory " + organization + File.separator + repoName
```
Comment (eugenepeh) [inline src/main/java/reposense/git/GitCloner.java]: I think here should throw `GitClonerException` because it can't proceed anymore without downloading the repo.

File: src/functional/java/reposense/Entry.java [hunk 5]
```diff
@@ -21,63 +25,71 @@
...
-    private void verifyAllJson(File expectedDirectory, String actualRelative) {
-        for (File file : expectedDirectory.listFiles()) {
-            if (file.isDirectory()) {
-                verifyAllJson(file, actualRelative);
-            } else {
-                if (!file.getName().endsWith(".js")) {
-                    continue;
+    private void verifyAllJson(Path expectedDirectory, String actualRelative) {
+        try (Stream<Path> pathStream = Files.list(expectedDirectory)) {
+            pathStream.forEach(filePath -> {
```
Comment (Zhiyuan-Amos) [inline src/functional/java/reposense/Entry.java]: Wondering if we should remain using a standard `for loop` instead (see [8.1. Avoid Blocks of Code in Lambda’s Body](http://www.baeldung.com/java-8-lambda-expressions-tips). :P

Comment (eugenepeh) [reply src/functional/java/reposense/Entry.java]: @Zhiyuan-Amos interested in helping out with RepoSense? ^^

Good catch, I agree that it defeats the purpose of lambda expression.

Comment (eugenepeh) [reply src/functional/java/reposense/Entry.java]: @yamidark 

He mean retain the old for loop instead of using lambda expression e.g.
```
for (...) {
  // that whole chunk...
}
```
AFAIK lambda expression doesn't speed up your code and is often
So throwing the chunk of code in that lambda's body defeat the purpose of functional programming and also doesn't help much in readability.

**Comment by yamidark** [comment]
@eugenepeh Ready for your review again.

File: src/main/java/reposense/util/FileUtil.java [hunk 6]
```diff
@@ -38,133 +37,49 @@ public static String getRepoDirectory(String org, String repoName) {
...
-                out.write(buffer, 0, length);
-            }
-
-            in.close();
-            out.close();
-        } catch (FileNotFoundException e) {
-            e.printStackTrace();
-        } catch (IOException e) {
-            e.printStackTrace();
+            Files.setAttribute(filePath, "dos:readonly", false);
```
Comment (eugenepeh) [inline src/main/java/reposense/util/FileUtil.java]: why need to set file attribute to readonly to delete it?

File: src/main/java/reposense/git/GitCloner.java (hunk 4 above)
Comment (eugenepeh) [reply src/main/java/reposense/git/GitCloner.java]: Would prefer not to print the message here, since its throwing to the higher level to handle the error.

File: src/test/java/reposense/analyzer/FileAnalyzerTest.java [hunk 7]
```diff
@@ -23,7 +22,7 @@ public void allFileTest() {
...
+        Assert.assertTrue(isFileExistence("newPos/movedFile.java", files));
```
Comment (eugenepeh) [inline src/test/java/reposense/analyzer/FileAnalyzerTest.java]: For the below function 

```
     private boolean isFileExistence(String filePath, List<FileInfo> files) {
         for (FileInfo file : files) {
             if (file.getPath().equals(filePath)) {
                 return true;
             }
         }
         return false;
     }
```

Instead of comparing strings, perhaps Paths will be better

File: src/test/java/reposense/template/GitTestTemplate.java [hunk 8]
```diff
@@ -34,13 +32,13 @@ public void before() {
     }
 
     @BeforeClass
-    public static void beforeClass() throws GitClonerException {
+    public static void beforeClass() throws Exception {
```
Comment (eugenepeh) [inline src/test/java/reposense/template/GitTestTemplate.java]: Instead of a generic Exception, perhaps throw the individual exceptions instead? So that we can trace back if error occurs.

**Comment by yamidark** [comment]
@eugenepeh Changes made, ready for review again

File: src/functional/java/reposense/Entry.java [hunk 9]
```diff
@@ -65,11 +73,15 @@ private void assertJson(File expectedJson, String expectedPosition, String actua
...
     private String getRelativeDir() {
-        for (File file : (new File(FT_TEMP_DIR)).listFiles()) {
-            if (file.getName().contains("DS_Store")) {
-                continue;
+        try (Stream<Path> pathStream = Files.list(Paths.get(FT_TEMP_DIR))) {
+            Optional<Path> optionalPath = pathStream
+                    .filter(filePath -> !filePath.toString().contains("DS_Store"))
+                    .findFirst();
+            if (optionalPath.isPresent()) {
+                return optionalPath.get().toString();
```
Comment (ongspxm) [inline src/functional/java/reposense/Entry.java]: some explanation would help, comments?

**Comment by eugenepeh** [comment]
@yong24s @ AdityaA1998 can you guys review this tomorrow too? Thanks.

File: src/functional/java/reposense/Entry.java [hunk 10]
```diff
@@ -20,43 +26,51 @@
...
-                verifyAllJson(file, actualRelative);
-            } else {
-                if (!file.getName().endsWith(".json")) {
-                    continue;
+    private void verifyAllJson(Path expectedDirectory, String actualRelative) {
+        try (Stream<Path> pathStream = Files.list(expectedDirectory)) {
+            for (Path filePath : pathStream.collect(Collectors.toList())) {
+                if (Files.isDirectory(filePath)) {
+                    verifyAllJson(filePath, actualRelative);
+                } else {
```
Comment (yong24s) [inline src/functional/java/reposense/Entry.java]: Can be simplified by removing the else {..}

```
if (Files.isDirectory(filePath)) {
    verifyAllJson(filePath, actualRelative);
}

if (filePath.toString().endsWith(".json")) {
                        String relativeDirectory = filePath.toAbsolutePath().toString().split(EXPECTED_FOLDER)[1];
                        assertJson(filePath, relativeDirectory, actualRelative);
}

```

File: src/main/java/reposense/analyzer/FileAnalyzer.java [hunk 11]
```diff
@@ -19,28 +21,27 @@
...
-                if (!relativePath.endsWith(".java") && !relativePath.endsWith(".adoc")) {
-                    continue;
+            RepoConfiguration config, Path directory, ArrayList<String> relativePaths) {
+        try (Stream<Path> pathStream = Files.list(directory)) {
+            for (Path filePath : pathStream.collect(Collectors.toList())) {
+                String relativePath = filePath.toString().substring(config.getRepoRoot().length());
+                if (shouldIgnore(relativePath, config.getIgnoreDirectoryList())) {
+                    return;
+                }
+                if (Files.isDirectory(filePath)) {
```
Comment (yong24s) [inline src/main/java/reposense/analyzer/FileAnalyzer.java]: Same as above.

**Comment by yamidark** [comment]
@ongspxm @yong24s For your review again

**Comment by yong24s** [comment]
Octocat says good work. :1st_place_medal:

**Comment by yamidark** [comment]
@damithc Prof for your review

**Comment by ongspxm** [comment]
finally can tag @yamidark
