### PR TITLE
Simplify CSV configuration file format #60 #138

### LINKED ISSUE #60: Ignore blank lines in the config file
Current: blank lines in the config file (csv) file can crash the app
Suggested: ignore such blank lines

### PR DESCRIPTION
**Pull request by yong24s**
This PR is a continuation of  #119 as PR 119 is wrongly reporting 500k of line of code changes.  

Fixes #60 and #138

Proposed message:

```
The format of the CSV configuration file requires all white listed
authors pertaining to a repository to be written in a line.

This design may degrade user-friendliness, as it may be
more difficult to add information horizontally for repository with
large number of contributors.

Let's change the format of the CSV configuration file to one author
per line, so that the experience of adding new user is consistent.
Thus, improving user experience.
```
Proposed New Format:

|     Organization     | Repository | branch | User Git ID | User Display Name |        User's Git Alias         |
|----------------------|------------|--------|-------------|-------------------|---------------------------------|
| CS2103AUG2017-W09-B1 | main       | master | nbriannl    |                   |                                 |
| CS2103AUG2017-W09-B1 | main       | master | zacharytang | Zachary Tang      | Zachary Tang                    |
| CS2103AUG2017-W09-B1 | main       | master | April0616   | Fan Yuting        | LAPTOP-7KFM2KSP\User;Fan Yuting |
| CS2103AUG2017-W09-B1 | main       | master | CindyTsai1  | Cindy Tsai        | YuHsuan                         |

### CODE REVIEW

**Comment by yong24s** [comment]
@eugenepeh @ongspxm @AdityaA1998  @yamidark
Please review.

File: src/main/java/reposense/dataobject/RepoConfiguration.java [hunk 1]
```diff
@@ -15,9 +15,8 @@
     private String repoName;
     private String branch;
     private String displayName;
-    private Date fromDate;
-    private Date toDate;
-
+    private Date sinceDate;
+    private Date untilDate;
     private transient boolean needCheckStyle = false;
```
Comment (yamidark) [inline src/main/java/reposense/dataobject/RepoConfiguration.java]: should have a newline to separate `private transient` from `private`, and `private` variables grouped together

File: src/main/java/reposense/parser/CsvParser.java [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+    private static final int DISPLAY_NAME_POSITION = 4;
+    private static final int ALIAS_POSITION = 5;
+
+    /** String format of the key for RepoConfig HashMap */
+    private static final String REPO_CONFIG_MAP_KEY_FORMAT = "%s|%s|%s";
+
+    /**
+     * Creates {@code RepoConfiguration} object in {@code repositoryMap}, if it does not exists.
+     *
+     * Parameters - organization, repositoryName and branch are used to create the key to access RepoMap.
```
Comment (yamidark) [inline src/main/java/reposense/parser/CsvParser.java]: `RepoMap` -> `repositoryMap`

File: src/main/java/reposense/parser/CsvParser.java [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+        return new ArrayList<RepoConfiguration>(repositoryMap.values());
+    }
+
+    private void processLine(HashMap<String, RepoConfiguration> repositoryMap,
+            Date sinceDate, Date untilDate, String line, int lineNumber) {
+        if (!line.isEmpty()) {
+            String[] elements = line.split(Constants.CSV_SPLITTER);
+
+            if (elements.length < GITHUB_ID_POSITION) {
+                // Warns incorrect lines and does not stop the program
```
Comment (yamidark) [inline src/main/java/reposense/parser/CsvParser.java]: `Warns of incorrect lines, and skips it`?

File: src/main/java/reposense/report/ContributionSummaryGenerator.java [hunk 4]
```diff
@@ -18,6 +18,7 @@
 
 public class ContributionSummaryGenerator {
 
+
```
Comment (yamidark) [inline src/main/java/reposense/report/ContributionSummaryGenerator.java]: unnecessary line break

File: src/functional/java/reposense/Entry.java [hunk 5]
```diff
@@ -22,21 +21,26 @@
...
+    private void generateReport() throws IOException {
         File configFile = new File(getClass().getClassLoader().getResource("sample_full.csv").getFile());
-        Calendar c = Calendar.getInstance();
-        c.set(2017, 6, 1);
-        Date fromDate = c.getTime();
-        c.set(2017, 10, 30);
-        Date toDate = c.getTime();
-        List<RepoConfiguration> configs = CsvConfigurationBuilder.buildConfigs(configFile, fromDate, toDate);
+        String[] args = new String[]{"-config", configFile.getAbsolutePath(),
+            "-since", "01/07/2017", "-until", "30/11/2017"};
```
Comment (eugenepeh) [inline src/functional/java/reposense/Entry.java]: this should be for unit test.

File: src/main/java/reposense/frontend/RepoSense.java [hunk 6]
```diff
@@ -17,17 +17,16 @@ public static void main(String[] args) {
...
             File targetFile = cliArguments.getTargetFile();
-            Date fromDate = cliArguments.getSinceDate().orElse(null);
-            Date toDate = cliArguments.getUntilDate().orElse(null);
 
-            List<RepoConfiguration> configs = CsvConfigurationBuilder.buildConfigs(configFile, fromDate, toDate);
+            List<RepoConfiguration> configs = csvParser.parse(cliArguments);
             RepoInfoFileGenerator.generateReposReport(configs, targetFile.getAbsolutePath());
-        } catch (IllegalArgumentException ex) {
-            System.out.print(ex.getMessage());
+        } catch (IllegalArgumentException iaex) {
```
Comment (eugenepeh) [inline src/main/java/reposense/frontend/RepoSense.java]: iae

File: src/main/java/reposense/frontend/RepoSense.java [hunk 7]
```diff
@@ -17,17 +17,16 @@ public static void main(String[] args) {
...
+            System.out.print(iaex.getMessage());
             showHelpMessage();
+        } catch (IOException ioex) {
```
Comment (eugenepeh) [inline src/main/java/reposense/frontend/RepoSense.java]: ioe

File: src/main/java/reposense/parser/CsvParser.java [hunk 8]
```diff
@@ -0,0 +1,158 @@
...
+import reposense.dataobject.RepoConfiguration;
+import reposense.frontend.CliArguments;
+import reposense.util.Constants;
+
+/**
+ * Parses a CSV configuration file for repository information.
+ */
+public class CsvParser {
+    private static final String MESSAGE_UNABLE_TO_READ_CSV_FILE = "Unable to read the supplied CSV file.";
+    private static final String MESSAGE_MALFORMED_LINE_FORMAT = "Warning! line %s is malformed.\n"
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: should use %d for integer

File: src/main/java/reposense/parser/CsvParser.java [hunk 9]
```diff
@@ -0,0 +1,158 @@
...
+    }
+
+    private String createRepoConfigKey(String organization, String repositoryName, String branch) {
+        return String.format(REPO_CONFIG_MAP_KEY_FORMAT, organization, repositoryName, branch);
+    }
+
+    /**
+     * Returns a list of {@code RepoConfiguration}, which are the inflated object a line of the csv file.
+     *
+     * @throws IOException If user-supplied csv file does not exists or is not readable.
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: if

File: src/main/java/reposense/parser/CsvParser.java [hunk 10]
```diff
@@ -0,0 +1,158 @@
...
+            }
+
+        } catch (IOException iex) {
+            throw new IOException(MESSAGE_UNABLE_TO_READ_CSV_FILE);
+        }
+
+        return new ArrayList<RepoConfiguration>(repositoryMap.values());
+    }
+
+    private void processLine(HashMap<String, RepoConfiguration> repositoryMap,
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: missing header comments

File: src/main/java/reposense/parser/CsvParser.java (hunk 8 above)
Comment (eugenepeh) [reply src/main/java/reposense/parser/CsvParser.java]: `in configuration file` is malformed.

File: template/static/scripts/utils.js [hunk 11]
```diff
@@ -190,9 +190,9 @@ function getMinDate() {
 }
 
 function getMaxDate() {
-    rawDate = summaryJson[Object.keys(summaryJson)[0]]["toDate"];
+    rawDate = summaryJson[Object.keys(summaryJson)[0]]["untilDate"];
     if (rawDate) {
-        //the fromDate has been set
+        //the sinceDate has been set
```
Comment (eugenepeh) [inline template/static/scripts/utils.js]: think this should be `until`

File: src/main/java/reposense/parser/CsvParser.java [hunk 12]
```diff
@@ -0,0 +1,158 @@
...
+            for (final String line : lines) {
+                processLine(repositoryMap, sinceDate, untilDate, line, lineNumber);
+                lineNumber++;
+            }
+
+        } catch (IOException iex) {
+            throw new IOException(MESSAGE_UNABLE_TO_READ_CSV_FILE);
+        }
+
+        return new ArrayList<RepoConfiguration>(repositoryMap.values());
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: the levels of abstraction in this method is quite uneven.

Also, can you try this instead?

If repoconfig exists -> add author
else -> create and add the repoconfig to the list.

File: src/main/java/reposense/parser/CsvParser.java [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+
+        return repoConfigurations;
+    }
+
+    /**
+     * Extracts {@code Author} information from the {@code line}.
+     */
+    private static void processLine(List<RepoConfiguration> repoConfigurations,
+            Date sinceDate, Date untilDate, String line, int lineNumber) {
+        if (!line.isEmpty()) {
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: Can use a guard clause to reduce nesting.
More info at https://se-edu.github.io/se-book/codeQuality/maximiseReadability/advanced/#make-happy-path-prominent

File: src/main/java/reposense/parser/CsvParser.java [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+        }
+    }
+
+    private static void setDisplayName(String[] elements, RepoConfiguration config, Author author) {
+        // Checks length of the elements array as trailing commas may be omitted for empty columns
+        if (elements.length > DISPLAY_NAME_POSITION && !elements[DISPLAY_NAME_POSITION].isEmpty()) {
+            //Not empty, take the supplied value as Display Name
+            config.getAuthorDisplayNameMap().put(author, elements[DISPLAY_NAME_POSITION]);
+        } else {
+            //else, use GitHub Id as Display Name
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: The word `else` id redundant

File: src/main/java/reposense/parser/CsvParser.java [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+            Author author = new Author(elements[GITHUB_ID_POSITION]);
+            config.getAuthorList().add(author);
+            setDisplayName(elements, config, author);
+            setAlias(elements, config, author);
+        }
+    }
+
+    private static void setDisplayName(String[] elements, RepoConfiguration config, Author author) {
+        // Checks length of the elements array as trailing commas may be omitted for empty columns
+        if (elements.length > DISPLAY_NAME_POSITION && !elements[DISPLAY_NAME_POSITION].isEmpty()) {
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: Perhaps use an explanatory variable to reduce the need for comments?
`... = elements.length > DISPLAY_NAME_POSITION && !elements[DISPLAY_NAME_POSITION].isEmpty()`

File: src/main/java/reposense/parser/CsvParser.java [hunk 16]
```diff
@@ -0,0 +1,126 @@
...
+            final Collection<String> lines = Files.lines(path).skip(SKIP_FIRST_LINE).collect(Collectors.toList());
+
+            for (final String line : lines) {
+                processLine(repoConfigurations, sinceDate, untilDate, line, lineNumber);
+                lineNumber++;
+            }
+
+        } catch (IOException ioe) {
+            throw new IOException(MESSAGE_UNABLE_TO_READ_CSV_FILE);
+        }
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: See if you can preserve the original exception as well. Otherwise we could be losing important information useful for debugging.

File: src/main/java/reposense/parser/CsvParser.java [hunk 17]
```diff
@@ -0,0 +1,126 @@
...
+
+import reposense.dataobject.Author;
+import reposense.dataobject.RepoConfiguration;
+import reposense.frontend.CliArguments;
+import reposense.util.Constants;
+
+/**
+ * Parses a CSV configuration file for repository information.
+ */
+public class CsvParser {
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: Did you consider using a third-party csv parser?

File: src/main/java/reposense/parser/CsvParser.java [hunk 18]
```diff
@@ -0,0 +1,126 @@
...
+
+        // Checks length of the elements array as trailing commas may be omitted for empty columns
+        // If more alias are provided, use them as well
+        if (elements.length > ALIAS_POSITION &&  !elements[ALIAS_POSITION].isEmpty()) {
+            String[] aliases = elements[ALIAS_POSITION].split(Constants.AUTHOR_ALIAS_SPLITTER);
+
+            for (String alias : aliases) {
+                config.getAuthorAliasMap().put(alias, author);
+            }
+        }
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: In general, try to make the code self-explanatory (e.g., [use explaining variables](https://refactoring.com/catalog/extractVariable.html)) to reduce the need for explanatory comments.

File: src/main/java/reposense/parser/CsvParser.java [hunk 19]
```diff
@@ -0,0 +1,126 @@
...
+     * Extracts {@code Author} information from the {@code line}.
+     */
+    private static void processLine(List<RepoConfiguration> repoConfigurations,
+            Date sinceDate, Date untilDate, String line, int lineNumber) {
+        if (!line.isEmpty()) {
+            String[] elements = line.split(Constants.CSV_SPLITTER);
+
+            if (elements.length < GITHUB_ID_POSITION) {
+                // Warns malformed line and skips it
+                System.out.println(String.format(MESSAGE_MALFORMED_LINE_FORMAT, lineNumber, line));
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: logger is not available at this point?

File: src/main/java/reposense/parser/CsvParser.java (hunk 17 above)
Comment (yong24s) [reply src/main/java/reposense/parser/CsvParser.java]: Currently, the Csv Parser is sufficient for our needs. We can look into third-party libraries if there exists use cases for it.

File: src/main/java/reposense/parser/CsvParser.java (hunk 18 above)
Comment (yong24s) [reply src/main/java/reposense/parser/CsvParser.java]: Prof, I made the changes. Please kindly review.

File: src/main/java/reposense/parser/CsvParser.java [hunk 20]
```diff
@@ -0,0 +1,135 @@
...
+    private static void processLine(List<RepoConfiguration> repoConfigurations,
+            Date sinceDate, Date untilDate, String line, int lineNumber) {
+        if (line.isEmpty()) {
+            return;
+        }
+
+        String[] elements = line.split(Constants.CSV_SPLITTER);
+
+        if (elements.length < GITHUB_ID_POSITION) {
+            // Warns malformed line and skips it
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: This comment applies to the while `if` block. Should be placed above the `if`. 
Anyway, probably no need for the comment as the code is clear enough.

File: src/main/java/reposense/parser/CsvParser.java [hunk 21]
```diff
@@ -0,0 +1,135 @@
...
+        RepoConfiguration config = new RepoConfiguration(organization, repositoryName, branch);
+        int index = repoConfigurations.indexOf(config);
+
+        if (index != -1) {
+            config = repoConfigurations.get(index);
+        } else {
+            repoConfigurations.add(config);
+            config.setSinceDate(sinceDate);
+            config.setUntilDate(untilDate);
+        }
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: Not clear what this `if` block is for. Add a comment just above it?

File: src/main/java/reposense/parser/CsvParser.java [hunk 22]
```diff
@@ -0,0 +1,135 @@
...
+        boolean isDisplayNameInElements = elements.length > DISPLAY_NAME_POSITION
+                && !elements[DISPLAY_NAME_POSITION].isEmpty();
+
+        if (isDisplayNameInElements) {
+            //Not empty, take the supplied value as Display Name
+            config.getAuthorDisplayNameMap().put(author, elements[DISPLAY_NAME_POSITION]);
+        } else {
+            //Use GitHub Id as Display Name
+            config.getAuthorDisplayNameMap().put(author, author.getGitId());
+        }
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: No need for comments: the code is clear enough.

File: src/main/java/reposense/parser/CsvParser.java [hunk 23]
```diff
@@ -0,0 +1,135 @@
...
+    }
+
+    private static void setAlias(String[] elements, RepoConfiguration config, Author author) {
+        //Always use GitHub Id as an alias
+        config.getAuthorAliasMap().put(elements[GITHUB_ID_POSITION], author);
+        // If more aliases are provided, use them as well
+        boolean isAliasPositionInElements = elements.length > ALIAS_POSITION
+                && !elements[ALIAS_POSITION].isEmpty();
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: When you add comments like this, the reader will take the comment as applicable to the code block immediately below it. That's not the case here. You are better of adding a header comment to the whole method instead of these inline comments.

**Comment by yong24s** [comment]
@damithc Prof, for your review, please.

File: src/main/java/reposense/parser/CsvParser.java [hunk 24]
```diff
@@ -0,0 +1,138 @@
...
+            repoConfigurations.add(config);
+        }
+
+        Author author = new Author(elements[GITHUB_ID_POSITION]);
+        config.getAuthorList().add(author);
+        setDisplayName(elements, config, author);
+        setAliases(elements, config, author);
+    }
+
+    private static void setDisplayName(String[] elements, RepoConfiguration config, Author author) {
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: Write a header comment for this.

File: src/main/java/reposense/parser/CsvParser.java [hunk 25]
```diff
@@ -0,0 +1,138 @@
...
+        boolean isDisplayNameInElements = elements.length > DISPLAY_NAME_POSITION
+                && !elements[DISPLAY_NAME_POSITION].isEmpty();
+
+        if (isDisplayNameInElements) {
+            //Not empty, take the supplied value as Display Name
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: This comment is redundant.

File: src/main/java/reposense/parser/CsvParser.java [hunk 26]
```diff
@@ -0,0 +1,138 @@
...
+            config.getAuthorDisplayNameMap().put(author, elements[DISPLAY_NAME_POSITION]);
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: Add a `setDisplayName()` method to the `config` object?

File: src/main/java/reposense/parser/CsvParser.java [hunk 27]
```diff
@@ -0,0 +1,138 @@
...
+    private static void setAliases(String[] elements, RepoConfiguration config, Author author) {
+        config.getAuthorAliasMap().put(elements[GITHUB_ID_POSITION], author);
+        boolean isAliasPositionInElements = elements.length > ALIAS_POSITION
+                && !elements[ALIAS_POSITION].isEmpty();
+
+        if (isAliasPositionInElements) {
+            String[] aliases = elements[ALIAS_POSITION].split(Constants.AUTHOR_ALIAS_SPLITTER);
+
+            for (String alias : aliases) {
+                config.getAuthorAliasMap().put(alias, author);
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: have a `config.setAliases(...)` method.

File: src/main/java/reposense/frontend/RepoSense.java [hunk 28]
```diff
@@ -15,10 +17,19 @@
 
     private static final Logger logger = LogsManager.getLogger(RepoSense.class);
 
+    private static void setDatesToRepoConfigs(List<RepoConfiguration> configs,
+                                              Optional<Date> sinceDate, Optional<Date> untilDate) {
```
Comment (eugenepeh) [inline src/main/java/reposense/frontend/RepoSense.java]: This static method can probably be shifted to `RepoConfiguration` or, if there are many such methods, create a `ConfigurationUtil`.

File: src/main/java/reposense/frontend/RepoSense.java [hunk 29]
```diff
@@ -1,32 +1,39 @@
...
-            Path configFile = cliArguments.getConfigFilePath();
-            Path targetFile = cliArguments.getOutputFilePath();
-            Date fromDate = cliArguments.getSinceDate().orElse(null);
-            Date toDate = cliArguments.getUntilDate().orElse(null);
-
-            List<RepoConfiguration> configs = CsvConfigurationBuilder.buildConfigs(configFile, fromDate, toDate);
-            RepoInfoFileGenerator.generateReposReport(configs, targetFile.toAbsolutePath().toString());
+            List<RepoConfiguration> configs = CsvParser.parse(cliArguments.getConfigFilePath());
+            setDatesToRepoConfigs(configs, cliArguments.getSinceDate(), cliArguments.getUntilDate());
+            RepoInfoFileGenerator.generateReposReport(configs,
```
Comment (eugenepeh) [inline src/main/java/reposense/frontend/RepoSense.java]: use higher level break
```
RepoInfoFileGenerator.generateReposReport(
        configs, cliArguments.getOutputFilePath().toAbsolutePath().toString());
```

File: src/main/java/reposense/parser/CsvParser.java [hunk 30]
```diff
@@ -0,0 +1,126 @@
...
+
+    /**
+     * Extracts {@code Author} information from the {@code line}.
+     */
+    private static void processLine(List<RepoConfiguration> repoConfigurations, String line, int lineNumber) {
+        if (line.isEmpty()) {
+            return;
+        }
+
+        String[] elements = line.split(Constants.CSV_SPLITTER);
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: If this is the only class that depends on this `CSV_SPLITTER` constant, initialize it in this class.
Also, use a more appropriate name maybe like `ELEMENT_SEPARATOR` or something, because CSV itself already implies comma separated.

File: src/main/java/reposense/parser/CsvParser.java [hunk 31]
```diff
@@ -0,0 +1,126 @@
...
+
+        } catch (IOException ioe) {
+            throw new IOException(MESSAGE_UNABLE_TO_READ_CSV_FILE, ioe);
+        }
+
+        return repoConfigurations;
+    }
+
+    /**
+     * Extracts {@code Author} information from the {@code line}.
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]:
```
...
Adds the {@code Author} to its corresponding {@RepoConfiguration} if it exists, or creates a new 
{@RepoConfiguration} containing the {@code Author} and add it to the {@code repoConfigurations} otherwise.
```

File: src/main/java/reposense/parser/CsvParser.java [hunk 32]
```diff
@@ -0,0 +1,126 @@
...
+        }
+
+        Author author = new Author(elements[GITHUB_ID_POSITION]);
+        config.getAuthorList().add(author);
+        setDisplayName(elements, config, author);
+        setAliases(elements, config, author);
+    }
+
+    /**
+     * Associates display name from {@elements} to {@code author}, if provided.
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: tag error `{@elements}`

File: src/main/java/reposense/parser/CsvParser.java [hunk 33]
```diff
@@ -0,0 +1,129 @@
...
+        } catch (IOException ioe) {
+            throw new IOException(MESSAGE_UNABLE_TO_READ_CSV_FILE, ioe);
+        }
+
+        return repoConfigurations;
+    }
+
+    /**
+     * Adds the {@code Author} to its corresponding {@RepoConfiguration} if it exists, or creates a new
+     * {@RepoConfiguration} containing the {@code Author} and add it to the {@code repoConfigurations} otherwise.
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: `@code RepoConfiguration`

File: src/main/java/reposense/parser/CsvParser.java [hunk 34]
```diff
@@ -0,0 +1,129 @@
...
+
+        if (isDisplayNameInElements) {
+            config.setAuthorDisplayName(author, elements[DISPLAY_NAME_POSITION]);
+        } else {
+            config.setAuthorDisplayName(author, author.getGitId());
+        }
+    }
+
+    /**
+     * Associates github id and additional aliases in {@elements} to {@code author}.
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: `@code elements`

File: src/main/java/reposense/parser/CsvParser.java [hunk 35]
```diff
@@ -0,0 +1,129 @@
...
+import reposense.dataobject.Author;
+import reposense.dataobject.RepoConfiguration;
+import reposense.system.LogsManager;
+
+/**
+ * Parses a CSV configuration file for repository information.
+ */
+public class CsvParser {
+    private static final String ELEMENT_SEPARATOR = ",";
+    private static final String AUTHOR_ALIAS_SPLITTER = ";";
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: `AUTHOR_ALIAS_SPLITTER ` -> `AUTHOR_ALIAS_SEPARATOR` for standardization

File: src/main/java/reposense/parser/CsvParser.java [hunk 36]
```diff
@@ -0,0 +1,129 @@
...
+        } catch (IOException ioe) {
+            throw new IOException(MESSAGE_UNABLE_TO_READ_CSV_FILE, ioe);
+        }
+
+        return repoConfigurations;
+    }
+
+    /**
+     * Adds the {@code Author} to its corresponding {@code RepoConfiguration} if it exists, or creates a new
+     * {@RepoConfiguration} containing the {@code Author} and add it to the {@code repoConfigurations} otherwise.
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/CsvParser.java]: `@code`

**Comment by eugenepeh** [comment]
Nits in proposed message:

The format of the CSV configuration file requires all ~information~`white listed authors`
pertaining to a repository to be written in a line.

This design may degrade ~user experience of users~`user-friendliness`, ~who wish 
to track a repository with large number of contributors,~ as it may be
more difficult to add information horizontally `for repository with large number of contributors.`

Let's change the format of the CSV configuration file to ~each user~`one author`
per line, so that the experience of adding new user is consistent. 
Thus, improving user experience.

**Comment by yong24s** [comment]
@damithc Prof. for your review, please.

File: src/main/java/reposense/parser/CsvParser.java [hunk 37]
```diff
@@ -0,0 +1,129 @@
...
+     */
+    private static void setDisplayName(String[] elements, RepoConfiguration config, Author author) {
+        boolean isDisplayNameInElements = elements.length > DISPLAY_NAME_POSITION
+                && !elements[DISPLAY_NAME_POSITION].isEmpty();
+
+        if (isDisplayNameInElements) {
+            config.setAuthorDisplayName(author, elements[DISPLAY_NAME_POSITION]);
+        } else {
+            config.setAuthorDisplayName(author, author.getGitId());
+        }
```
Comment (damithc) [inline src/main/java/reposense/parser/CsvParser.java]: How about this?
```java
config.setAuthorDisplayName(author, 
    isDisplayNameInElements ? elements[DISPLAY_NAME_POSITION] : author.getGitId());
```
