### PR TITLE
[#872] CsvParser: improve exception handling when a csv file has incorrect number of columns in header

### LINKED ISSUE #872: ConfigCsvFiles: Improve exception handling when the csv file(s) is/are malformed
For example, `author-config.csv` should contain 7 columns (especially the headers). However, the user provided 6 columns (fewer columns than requred).

When program is run, exception is caught but the program is terminated abruptly, without giving the user enough info as to where went wrong:
image

###To-do
Improve on the exception handling, by informing the user that the csv file does not contain the required number of columns

### PR DESCRIPTION
**Pull request by anubh-v**
Fixes #872 

```
CsvParser: Improve exception handling when CSV has invalid header size

RepoSense crashes abruptly when any of the CSV config files
do not have the expected number of columns in their headers.

We should catch this error early and provide the user with a
clearer error message.

Let's add a header validation step to the CSV parsing process.
This step will verify if the CSV file's header has the right
number of columns.
```

### CODE REVIEW

**Comment by anubh-v** [comment]
@eugenepeh, @jylee-git, may I get your thoughts on this PR?

There is one limitation in the current solution.
The `parse` method in `CsvParser` will throw an `IOException` when the CSV file's header has the wrong number of columns.

However, the main code in `RepoSense.java` will silently ignore the `IOException` for the `author-config.csv` and `group-config.csv` files.

Ideally, the users should be alerted that the `author-config.csv` and `group-config.csv` are malformed, so they can fix the files and re-run the analysis.

Proposed fix: Throw `InvalidCsvException` out from `parse` in `CsvParser`.

I did not make this fix yet because it will affect many test files and significantly increase the size of the PR. 

I can make this change once the core logic of this PR is approved, or perhaps in another PR.

**Comment by anubh-v** [comment]
Hi everyone, could I get any team member's help to set the "toReview" label for this PR?
I don't have the permissions for that. Thanks!

**Comment by eugenepeh** [comment]
@anubh-v I have sent you the invite to become repository member, let me know if you didn't receive it.

**Comment by anubh-v** [comment]
@eugenepeh, thanks for the invite.

File: src/main/java/reposense/parser/CsvParser.java [hunk 1]
```diff
@@ -195,6 +200,20 @@ private String getRowContentAsRawString(final CSVRecord record) {
         return contentAsString;
     }
 
+    /**
+     * Checks if a given header has the right number of columns.
+     * @throws InvalidCsvException if the header does not have as many columns as expected.
+     */
+    private void validateHeader(String[] possibleHeader) throws InvalidCsvException {
```
Comment (jylee-git) [inline src/main/java/reposense/parser/CsvParser.java]: For the javadocs, let's include the input argument in the docs wherever possible.

`Checks if {@code possibleHeader} contains the expected number of columns. ...`

File: src/main/java/reposense/parser/CsvParser.java [hunk 2]
```diff
@@ -207,4 +226,9 @@ private String getRowContentAsRawString(final CSVRecord record) {
      * {@code record} and add created objects into {@code results}.
      */
     protected abstract void processLine(List<T> results, final CSVRecord record) throws ParseException;
+
+    /**
+     * Gets the number of columns expected in the header.
```
Comment (jylee-git) [inline src/main/java/reposense/parser/CsvParser.java]: Better starting word to use  here (same for those below) is `Returns the number of expected cols ...`

File: src/test/java/reposense/parser/CsvParserTest.java [hunk 3]
```diff
@@ -229,6 +231,12 @@ public void authorConfig_invalidLocation_success() throws IOException {
         Assert.assertEquals(3, config.getAuthorList().size());
     }
 
+    @Test (expected = IOException.class)
+    public void authorConfig_invalidHeaderSize_throwsIoException() throws IOException {
+        AuthorConfigCsvParser authorConfigCsvParser = new AuthorConfigCsvParser(AUTHOR_CONFIG_INVALID_HEADER_SIZE);
+        authorConfigCsvParser.parse();
+    }
```
Comment (jylee-git) [inline src/test/java/reposense/parser/CsvParserTest.java]: Do the same set of test cases for group and repo config  as well

File: src/main/java/reposense/parser/GroupConfigCsvParser.java [hunk 4]
```diff
@@ -79,4 +84,12 @@ private static GroupConfiguration findMatchingGroupConfiguration(
         results.add(config);
         return config;
     }
+
+    /**
+     * Gets the number of columns expected in the header.
```
Comment (jylee-git) [inline src/main/java/reposense/parser/GroupConfigCsvParser.java]: Be more specific in which header are we referring to here (in this case the group config header). Same for the other two

File: src/main/java/reposense/parser/CsvParser.java [hunk 5]
```diff
@@ -207,4 +226,9 @@ private String getRowContentAsRawString(final CSVRecord record) {
...
+     */
+    protected abstract int getHeaderSize();
```
Comment (fzdy1914) [inline src/main/java/reposense/parser/CsvParser.java]: Since `HEADER_SIZE` is a feature that all its child have, instead of an abstract method, is it better to make it a protected attribute and the child only need to overwrite this attribute and no need to overwite the method again and again?

**Comment by fzdy1914** [comment]
> Hi everyone, could I get any team member's help to set the "toReview" label for this PR?
> I don't have the permissions for that. Thanks!

For PR reviewing process, please only ask `stage1-reviewer` to review the PR first instead of both `stage1-reviewer` and `stage2-reviewer`.

**Comment by anubh-v** [comment]
Thanks very much for your time @jylee-git, @fzdy1914. 
I will respond to the feedback by tonight.

> For PR reviewing process, please only ask stage1-reviewer to review the PR first instead of both stage1-reviewer and stage2-reviewer.

My apologies for this. I have corrected this for my other open PR.

File: src/main/java/reposense/parser/CsvParser.java (hunk 1 above)
Comment (anubh-v) [reply src/main/java/reposense/parser/CsvParser.java]: Done

File: src/test/java/reposense/parser/CsvParserTest.java (hunk 3 above)
Comment (anubh-v) [reply src/test/java/reposense/parser/CsvParserTest.java]: Done

File: src/main/java/reposense/parser/CsvParser.java (hunk 5 above)
Comment (anubh-v) [reply src/main/java/reposense/parser/CsvParser.java]: Thanks for the suggestion.

What about keeping the expected header size as a private variable in `CsvParser` ? 
This variable can be set in the constructor of `CsvParser`.

File: src/main/java/reposense/parser/CsvParser.java [hunk 6]
```diff
@@ -36,20 +36,25 @@
...
 
     private Path csvFilePath;
+    private int expectedHeaderSize;
     private int numOfLinesBeforeFirstRecord = 0;
 
     /**
      * @throws IOException if {@code csvFilePath} is an invalid path.
      */
-    public CsvParser(Path csvFilePath) throws IOException {
+    public CsvParser(Path csvFilePath, int expectedHeaderSize) throws IOException {
```
Comment (anubh-v) [inline src/main/java/reposense/parser/CsvParser.java]: @fzdy1914, @jylee-git, do you think we can could keep the expected header size as a private variable in `CsvParser` like this?

With this approach, each child just needs to pass in the correct value of `expectedHeaderSize` when calling the constructor of the superclass.

File: src/main/java/reposense/parser/CsvParser.java (hunk 5 above)
Comment (fzdy1914) [reply src/main/java/reposense/parser/CsvParser.java]: I agree with your point. Go ahead.

File: src/main/java/reposense/parser/CsvParser.java (hunk 6 above)
Comment (fzdy1914) [reply src/main/java/reposense/parser/CsvParser.java]: I think it is a good approach. Do request a review from us again after you have finished everything.

File: src/main/java/reposense/parser/CsvParser.java (hunk 2 above)
Comment (anubh-v) [reply src/main/java/reposense/parser/CsvParser.java]: I removed the `getHeader` method entirely, since we are passing the expected header size to the constructor of `CsvParser`

File: src/main/java/reposense/parser/GroupConfigCsvParser.java (hunk 4 above)
Comment (anubh-v) [reply src/main/java/reposense/parser/GroupConfigCsvParser.java]: Thanks for the feedback. I removed the getHeader method entirely, since we are passing the expected header size to the constructor of CsvParser

**Comment by anubh-v** [comment]
@jylee-git, @fzdy1914, I have made changes to your feedback.

I removed the `getHeader` method entirely, and chose to pass the expected header size via the constructor of `CsvParser` instead.

**Comment by fzdy1914** [comment]
@anubh-v Thanks for the effort. You may choose to resolve the comment by yourself if you think the comment is trivial or you have solve the request.

**Comment by anubh-v** [comment]
@jylee-git, @fzdy1914,
There is one limitation in the current solution.
The `parse` method in `CsvParser` will throw an `IOException` when the CSV file's header has the wrong number of columns.

However, the driver code in RepoSense.java will silently ignore the `IOException` for the `author-config.csv` and `group-config.csv` files.

Ideally, the users should be alerted that the `author-config.csv` and `group-config.csv` are malformed, so they can fix the files and re-run the analysis.

Proposed fix: Throw `InvalidCsvException` out from `parse` in `CsvParser`, and use it to log a warning for `author-config.csv` and `group-config.csv`, in the `RepoSense.java` code.

Should this fix be done within this PR, or separately? *It will significantly increase the PR size as changing the `throws` clause of the `parse` method will affect many existing test cases*.

File: src/main/java/reposense/RepoSense.java [hunk 7]
```diff
@@ -93,17 +94,23 @@ public static void main(String[] args) {
         try {
             authorConfigs = new AuthorConfigCsvParser(cliArguments.getAuthorConfigFilePath()).parse();
             RepoConfiguration.merge(repoConfigs, authorConfigs);
-        } catch (IOException ioe) {
-            // IOException thrown as author-config.csv is not found.
+        } catch (FileNotFoundException fnfe) {
```
Comment (anubh-v) [inline src/main/java/reposense/RepoSense.java]: @jylee-git, @fzdy1914, I added a `catch` block here so we can warn the user if the author / group config files have an invalid header size (rather than silently ignoring the problem).

Should this be done within this PR, or separately?

Comment (fzdy1914) [reply src/main/java/reposense/RepoSense.java]: > Throw InvalidCsvException out from parse in CsvParser, and use it to log a warning for author-config.csv and group-config.csv, in the driver RepoSense.java code.

Hi, can you consider my Logic? Since we are dealing with CSV files, how about we directly set the `InvalidCsvException` a child of `IOException`. Then, instead of catching `FileNotFoundException`, we catch `InvalidCsvException` here and do the warning. We still leave the other `IOException` unhandled. In the meantime, we do not need to tough the test case a lot as it is a child of `IOException`.

Comment (anubh-v) [reply src/main/java/reposense/RepoSense.java]: But then we will be silently ignoring the IOExceptions besides the InvalidCsvException, right?
Would it be better to warn user about all IOExceptions that occur while parsing author and group configs, so the user can re-run the analysis ?

Comment (fzdy1914) [reply src/main/java/reposense/RepoSense.java]: OK, let's ask the senior's opinion. @yong24s @eugenepeh Your inputs, please?

Comment (eugenepeh) [reply src/main/java/reposense/RepoSense.java]: why is `FileNotFoundException` used for `if the author / group config files have an invalid header size`?

Comment (fzdy1914) [reply src/main/java/reposense/RepoSense.java]: His implementation is only ignoring `FileNotFoundException` instead of ignoring all `IOException` as we previously did.

Comment (anubh-v) [reply src/main/java/reposense/RepoSense.java]: @eugenepeh,  `FileNotFoundException` **will not** be thrown if the config files have an invalid header size. The `parse` method in `CsvParser` will throw an `IOException` if the config files have an invalid header size.

In our current implementation, we are silently ignoring all `IOExceptions` which are thrown while parsing author / group config files. However, it would be better to alert the user if the author / group configs have an invalid header size (or any other problem with the file).

Hence, I decided to distinguish between the case where the author / group config **is not present** and the case where the author / group config **is present but cannot be parsed because they are malformed / other IO error.**

The `FileNotFound` catch-block covers the first case (author / group config **is not present**).

Comment (eugenepeh) [reply src/main/java/reposense/RepoSense.java]: I see, sounds good to me

File: src/main/java/reposense/parser/GroupConfigCsvParser.java [hunk 8]
```diff
@@ -23,8 +23,13 @@
     private static final int GROUP_NAME_POSITION = 1;
     private static final int FILES_GLOB_POSITION = 2;
 
+    /**
+     * Number of columns expected in the header of repo-config.csv file.
+     */
+    private static final int HEADER_SIZE = 3;
```
Comment (eugenepeh) [inline src/main/java/reposense/parser/GroupConfigCsvParser.java]: can we do something like `EXPECTED_HEADER_SIZE = FILES_GLOB_POSITION + 1 // last position + 1`?

I would prefer it to be together with all the `POSITION` constants so that no one will forget to update it.

Comment (anubh-v) [reply src/main/java/reposense/parser/GroupConfigCsvParser.java]: Done.

Comment (eugenepeh) [reply src/main/java/reposense/parser/GroupConfigCsvParser.java]: Either is fine with me, but all the comments e.g.
```
    // Number of columns expected in the header of repo-config.csv file.
```
is rather redundant to me as this comment should be in the header comments of `CsvParser` instead.

Do add the inline comment `// last position + 1` so that subsequent developers would be reminded to update it

Comment (anubh-v) [reply src/main/java/reposense/parser/GroupConfigCsvParser.java]: Done. I've added the inline comment `// last position + 1` 
On second thought, perhaps we do not need a header comment in `CsvParser` as the attribute name (`expectedHeaderSize`) is self explanatory.

**Comment by anubh-v** [comment]
@fzdy1914, @jylee-git, may I get your review on the changes? Thanks very much.

File: src/main/java/reposense/parser/CsvParser.java [hunk 9]
```diff
@@ -36,20 +37,25 @@
...
         if (csvFilePath == null || !Files.exists(csvFilePath)) {
-            throw new IOException("Csv file does not exists in given path.\n"
+            throw new FileNotFoundException("Csv file does not exists in given path.\n"
```
Comment (jylee-git) [inline src/main/java/reposense/parser/CsvParser.java]: Csv file does not exist   ~s~

Comment (anubh-v) [reply src/main/java/reposense/parser/CsvParser.java]: Done

**Comment by yong24s** [comment]
@anubh-v 

Can you fix the tests? Thanks :-)

**Comment by anubh-v** [comment]
@jamessspanggg, @yong24s, I've resolved the conflict and fixed the tests
